import raw from "@/data/manifest.json";
import type { Manifest } from "./types";

/**
 * Every file in the study vault, grouped by folder. Generated by
 * `npm run manifest`, which scans the vault on your machine.
 * This module is the single source of truth for "does this file exist?".
 */
export const MANIFEST = raw as Manifest;

export const FILE_SET: Set<string> = new Set<string>();
for (const [dir, files] of Object.entries(MANIFEST)) {
  for (const f of files) FILE_SET.add(dir === "." ? f : `${dir}/${f}`);
}

export const TOTAL_FILES = FILE_SET.size;
export const TOTAL_FOLDERS = Object.keys(MANIFEST).length;

export function exists(p: string): boolean {
  return FILE_SET.has(p);
}

/** Collapse `.` and `..` segments. */
export function normPath(p: string): string {
  const out: string[] = [];
  for (const part of String(p).split("/")) {
    if (!part || part === ".") continue;
    if (part === "..") out.pop();
    else out.push(part);
  }
  return out.join("/");
}

export function filesIn(dir: string): string[] {
  return MANIFEST[dir || "."] ?? [];
}

export function subDirs(root: string): string[] {
  return Object.keys(MANIFEST)
    .filter((k) => k === root || k.startsWith(root + "/"))
    .sort();
}

export function descendantFileCount(root: string): number {
  return subDirs(root).reduce((n: number, k) => n + filesIn(k).length, 0);
}

export function dirFiles(dir: string, filter?: string): string[] {
  const files = filesIn(dir);
  if (!filter) return files;
  const f = filter.toLowerCase();
  return files.filter((x) => x.toLowerCase().startsWith(f));
}

export function fileName(p: string): string {
  return p.split("/").pop() ?? p;
}

/** Human label for a folder row in the file index. */
export function folderLabel(dir: string): string {
  return dir === "." ? "(vault root)" : dir;
}
