import type { Week } from "./types";

/**
 * The 8-week study plan, ported verbatim from Study_Dashboard.html.
 * Every path in here is relative to the vault and resolves against data/manifest.json.
 */
export const PLAN: Week[] = [
{week:1,title:"C Basics",range:"Mon 14 Sep → Sun 20 Sep",days:[
 {id:"w1d1",dow:"Mon",date:"2026-09-14",subject:"C",topic:"What is C, how a program runs, main(), printf, tokens",
  folder:"C_Programming_ClassWork/CProgramming/Day1",
  pdf:["C_Programming_Day1.pdf","C_Programming_Day2.pdf","Diagram_CProg_Day1_Part1.pdf","Diagram_CProgramming_Dat1_Part2.xopp"],
  img:["ASCII.png","ProgramFuncStmt_Token.png"],
  codeDir:"code",
  mcq:["../MCQ/Day01_MCQ.pdf"],poll:["../POLL/Day01_POll_Questions.pdf"],
  note:"C-CAT Section B gives 10-12 C questions — highest weightage! Topics: History of C, Keywords, Data Types (int/char/float/double + modifiers: short/long/signed/unsigned), Type Qualifiers (const/volatile). Tokens: keywords, identifiers, constants, strings, special symbols.",
  hint:"Foundation day. If C is strong, DS + C++ will be easier. Compilation steps samjho: Preprocessor → Compiler → Assembler → Linker. printf/scanf format specifiers %d %f %c %s %ld %lf — exam mein output prediction aata hai."},
 {id:"w1d2",dow:"Tue",date:"2026-09-15",subject:"C",topic:"Identifiers, keywords, data types, variables",
  folder:"C_Programming_ClassWork/CProgramming/Day2",
  pdf:["C_Programming_Day1.pdf","C_Programming_Day3.pdf","C_Programming_Day4.pdf","Diagram_Day3_CProg.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day02_MCQ.pdf"],poll:["../POLL/Day02_POll_Questions.pdf"],
  note:"Operators: Priority & Associativity table yaad karo — exam mein expression evaluation aata hai. Decision control: if-else, switch-case (break mat bhoolna). Iteration: while, do-while, for + jump statements (break, continue, goto, return).", 
  hint:"Folder naming off-by-one: Day2's actual lecture C_Programming_Day2.pdf is in the Day1/ folder. Output prediction practice karo — if(a=5) kya karega? (assignment, not comparison)."},
 {id:"w1d3",dow:"Wed",date:"2026-09-16",subject:"C",topic:"Operators (priority & associativity)",
  folder:"C_Programming_ClassWork/CProgramming/Day3",
  pdf:["C_Programming_Day4.pdf","Diagrams_CProg_Day3.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day03_MCQ.pdf"],poll:["../POLL/Day03_POll_Questions.pdf"],
  note:"Operator precedence: () [] -> . > ! ~ ++ -- (unary) > * / % > + - > << >> > < <= >= > == != > & > ^ > | > && > || > ?: > = += etc. Short-circuit evaluation: if(a && b) — agar a=false toh b check nahi hoga.",
  hint:"Day3's lecture C_Programming_Day3.pdf is in the previous folder (Day2/). Diagrams are in the right place. sizeof() operator yaad karo — sizeof(int) = 4, sizeof(char) = 1. Bitwise operators: & | ^ ~ << >> — interview mein puchte hain."},
 {id:"w1d4",dow:"Thu",date:"2026-09-17",subject:"C",topic:"Control flow: if / else, switch",
  folder:"C_Programming_ClassWork/CProgramming/Day4",
  pdf:["Day5.pdf","Day6.pdf","Diagrams_CProg_Day4_Part1.pdf","Diagrams_CProg_Day4_Part2.pdf"],
  img:["Screenshot 2024-04-12 120112.png","Screenshot 2024-04-12 120146.png","Screenshot 2024-04-12 121529.png","Screenshot 2024-04-12 121554.png","Screenshot 2024-11-18 113419.png","Screenshot 2024-11-18 113542.png","Screenshot 2024-11-18 113606.png","Screenshot 2024-11-18 113637.png"],
  codeDir:"code",
  mcq:["../MCQ/Day04_MCQ.pdf"],poll:["../POLL/Day04_POll_Questions.pdf"],
  note:"Switch-case: default case optional hai, break nahi toh fall-through hota hai. Nested if-else mein dangling else nearest if se attach hota hai. Ternary operator: (condition) ? true_val : false_val.",
  hint:"Day4's lecture C_Programming_Day4.pdf is in Day3/ (and Day2/). Output prediction: switch(3) { case 1: printf(\"1\"); case 3: printf(\"3\"); default: printf(\"D\"); } → 3D (fall-through)."},
 {id:"w1d5",dow:"Fri",date:"2026-09-18",subject:"C",topic:"Loops: while, do-while, for",
  folder:"C_Programming_ClassWork/CProgramming/Day5",
  pdf:["Day7.pdf","Day8.pdf","Diagram_CProg_Day5_Part1.pdf","Diagram_CProg_Day5_Part2.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day05_MCQ.pdf"],poll:["../POLL/Day05_POll_Questions.pdf"],
  note:"Loop types: while (pre-test), do-while (post-test, chalta kam se kam 1 baar), for (init; condition; increment). Infinite loops: while(1) or for(;;). Nested loops mein time complexity O(n²) hoti hai.",
  hint:"Infinite loop detection: while(i=1) — always true! break se loop se bahar aata hai, continue se next iteration pe jaata hai. goto interview mein mat use karo."},
 {id:"w1d6",dow:"Sat",date:"2026-09-19",subject:"Aptitude",topic:"Week-1 revision + Aptitude Day 1",
  folder:"suneam apptitude/Aptitude/Day_01",
  note:"C-CAT Section A: 50 questions (1 hour). English 12-15 Qs, Quant 15-18 Qs, Reasoning 12-15 Qs, Computer Fundamentals 5-6 Qs. Section A is easiest to improve — start with Number Systems, HCF/LCM, Percentages, Profit & Loss.",
  tasks:[
   {label:"Rewrite all Week 1 demo .c files from memory and run them",dirs:["C_Programming_ClassWork/CProgramming/Day1/code","C_Programming_ClassWork/CProgramming/Day2/code","C_Programming_ClassWork/CProgramming/Day3/code","C_Programming_ClassWork/CProgramming/Day4/code","C_Programming_ClassWork/CProgramming/Day5/code"]},
   {label:"Read Aptitude Day_01 lecture",detail:"suneam apptitude/Aptitude/Day_01/Apti_Day01.pdf"},
   {label:"Solve Aptitude MCQs + Poll",detail:"suneam apptitude/Aptitude/MCQs/Day01_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day01_POll_Questions.pdf"}]},
 {id:"w1d7",dow:"Sun",date:"2026-09-20",subject:"Revision",topic:"Rest + week revise",
  folder:null,
  tasks:[
   {label:"Skim Week 1 PDFs again"},
   {label:"Re-solve the MCQs you got wrong, without looking at answers"},
   {label:"Log this week's mistakes in the Weak Topics tab"}]}]},

{week:2,title:"C Core",range:"Mon 21 Sep → Sun 27 Sep",days:[
 {id:"w2d1",dow:"Mon",date:"2026-09-21",subject:"C",topic:"Functions, pass by value vs address, recursion",
  folder:"C_Programming_ClassWork/CProgramming/Day6",
  pdf:["Day8.pdf","Day9.pdf","Day10.pdf","Diagrams_CProg_Day6_Part1.pdf","Diagrams_CProg_Day6_Part2.pdf","Diagrams_CProg_Day6_Part3.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day06_MCQ.pdf"],poll:["../POLL/Day06_POll_Questions.pdf"],
  note:"Functions: built-in (printf, scanf, strlen) vs user-defined. Pass by value (copy hota hai, original change nahi hota) vs Pass by address (pointer use hota hai, original change hota hai). Recursion: base case + recursive case — stack memory use hoti hai.",
  hint:"Pass by value vs address is an exam favourite — write one program with each. Function pointer syntax: void (*fp)(int) = &func; — ye advanced topic hai but exam mein aa sakta hai."},
 {id:"w2d2",dow:"Tue",date:"2026-09-22",subject:"C",topic:"Storage classes, scope",
  folder:"C_Programming_ClassWork/CProgramming/Day7",
  pdf:["Day9.pdf","Day10.pdf","Diagram_CProg_Day7.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day07_MCQ.pdf"],poll:["../POLL/Day07_POll_Questions.pdf"],
  note:"Storage Classes: auto (default, stack), static (value retain hota hai, initialized once), extern (global, across files), register (CPU register mein). Scope: block vs function vs file. Lifetime: automatic vs static.",
  hint:"auto / static / extern / register — output-prediction questions come from here. static int x = 0; x++; — har call pe x badhta hai, 0 se start hoga, output: 1 2 3 4 5."},
 {id:"w2d3",dow:"Wed",date:"2026-09-23",subject:"C",topic:"Arrays (1D, 2D)",
  folder:"C_Programming_ClassWork/CProgramming/Day8",
  pdf:["Day10.pdf","Diagrams_CProg_Day8.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day08_MCQ.pdf"],poll:["../POLL/Day08_POll_Questions.pdf"],
  note:"Arrays: contiguous memory allocation. 1D: arr[5] = {1,2,3,4,5}. 2D: arr[3][4] — row-major order (C default). Array decay to pointer: arr[i] = *(arr+i). Static arrays: size compile-time pe known. Dynamic: malloc/calloc use karo.",
  hint:"Arrays + pointers interlinked hain. int arr[5] = {10,20,30,40,50}; *(arr+2) = 30. sizeof(arr) = 5*4 = 20 bytes. Array out-of-bounds: C mein error nahi aata, undefined behavior hota hai — exam mein output prediction mein puchte hain."},
 {id:"w2d4",dow:"Thu",date:"2026-09-24",subject:"C",topic:"Strings + library functions",
  folder:"C_Programming_ClassWork/CProgramming/Day9",
  pdf:["Day10.pdf","Day13.pdf","Diagram_CProg_Day9_annotated.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day09_MCQ.pdf"],poll:["../POLL/Day09_POll_Questions.pdf"],
  note:"Strings: char array terminated by '\0'. strlen() = size-1 (null count nahi karta). strcpy(dest, src), strcat(s1,s2), strcmp(s1,s2) — returns 0 if equal. String access via pointer: *(str+i) = str[i]. Multiple strings: 2D char array ya array of pointers.",
  hint:"String library functions: strlen, strcpy, strcat, strcmp, strncpy, strncat, strncmp, strstr, strchr, strrchr — ye sab yaad karo. Command line arguments: int main(int argc, char *argv[]) — argc = argument count, argv = argument vector."},
 {id:"w2d5",dow:"Fri",date:"2026-09-25",subject:"C",topic:"Pointers: wild / NULL / void, pointer arithmetic",
  folder:"C_Programming_ClassWork/CProgramming/Day10",
  pdf:["Day13.pdf","Diagram_CProg_Day10.pdf"],
  mcq:["../MCQ/Day10_MCQ.pdf"],poll:["../POLL/Day10_POll_Questions.pdf"],
  note:"Pointer types: Wild pointer (garbage value), NULL pointer (points to 0), Void pointer (generic, can't dereference directly). Pointer arithmetic: p+1 moves by sizeof(type) bytes. Function pointer: void (*fp)(int) = func; — callback pattern.",
  hint:"No code/ folder today — write your own programs. Pointers = highest marks topic. Pointer arithmetic: int *p = arr; *(p+1) = arr[1]. int *p = (int*)malloc(4); — malloc returns void*, cast karo. Double pointer: int **pp = &p — pointer to pointer."},
 {id:"w2d6",dow:"Sat",date:"2026-09-26",subject:"Aptitude",topic:"Aptitude Day 2 + ab tak ke quiz",
  folder:"suneam apptitude/Aptitude/Day_02",
  note:"Quant focus: Ratio & Proportion, Partnership, Average, Problems on Ages. These are high-frequency topics. Speed = Accuracy + Time management. Learn shortcuts: percentage to fraction conversion (25% = 1/4, 33.33% = 1/3).",
  tasks:[
   {label:"Read Apti_Day02.pdf",detail:"suneam apptitude/Aptitude/Day_02/Apti_Day02.pdf"},
   {label:"Solve Apti MCQs + Poll Day02",detail:"suneam apptitude/Aptitude/MCQs/Day02_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day02_POll_Questions.pdf"},
   {label:"Solve output-prediction questions from c quize.txt",detail:"quize pdfs/c quize.txt  (20 questions)"},
   {label:"Solve C questions from Quiz PDFs",detail:"quize pdfs/Quiz_Questions_and_Solutions.pdf"}]},
 {id:"w2d7",dow:"Sun",date:"2026-09-27",subject:"Revision",topic:"Rest + week revise",
  folder:null,
  tasks:[   {label:"Skim Week 2 PDFs"},{label:"Mid-point check: ~70% C syllabus done — test yourself"}]}]},

{week:3,title:"C finishing + Data Structures",range:"Mon 28 Sep → Sun 4 Oct",days:[
 {id:"w3d1",dow:"Mon",date:"2026-09-28",subject:"C",topic:"Pointers + arrays, dynamic memory (malloc/free)",
  folder:"C_Programming_ClassWork/CProgramming/Day11",
  pdf:["Day13.pdf","Day15.pdf","Diagram_CProg_Day11.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day11_MCQ.pdf"],poll:["../POLL/Day11_POll_Questions.pdf"],
  note:"Dynamic memory: malloc(size) — garbage values, calloc(n, size) — initializes to 0. realloc(ptr, new_size) — resize without data loss. free(ptr) — deallocate. Memory leak: free nahi kiya toh memory waste hoti hai. Dangling pointer: free ke baad pointer use karna = undefined behavior.",
  hint:"malloc/free + memory leak questions are guaranteed to appear. int *p = (int*)malloc(5*sizeof(int)); — 5 integers allocate karo. Array of pointers: int *arr[5] = {&a, &b, &c, &d, &e}. Pointer to array: int (*p)[10] — pointer to array of 10 ints."},
 {id:"w3d2",dow:"Tue",date:"2026-09-29",subject:"C",topic:"Structures, unions, bit fields",
  folder:"C_Programming_ClassWork/CProgramming/Day12",
  pdf:["Day15_1.pdf","Diagrams_CProg_Day12_Part1.pdf","Diagrams_CProg_Day12_Part2.pdf","Final_Day18.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day12_MCQ.pdf"],poll:["../POLL/Day12_POll_Questions.pdf"],
  note:"Structure: different data types ek saath. sizeof(struct) = sum of members (with padding). Union: sab members share karte hain same memory — sizeof = largest member. Bit fields: int flag:1; — 1 bit allocate karta hai. Access: dot (.) for structure, arrow (->) for pointer to structure.",
  hint:"struct vs union size — get into the habit of calculating it. struct { int a; char b; } → sizeof = 8 (with padding), union { int a; char b; } → sizeof = 4. Nested structures and arrays of structures bhi exam mein aate hain."},
 {id:"w3d3",dow:"Wed",date:"2026-09-30",subject:"C",topic:"Preprocessor, file handling",
  folder:"C_Programming_ClassWork/CProgramming/Day13",
  pdf:["Day18.pdf","Diagram_CProg_Day17.pdf"],
  img:["Screenshot 2024-10-17 115041.png"],
  codeDir:"code",
  mcq:["../MCQ/Day13_MCQ.pdf"],poll:["../POLL/Day13_POll_Questions.pdf"],
  note:"Preprocessor directives: #include (file include), #define (macro), #pragma (compiler specific). Macro vs Function: macro = preprocessor replace, function = runtime call. # and ## operators: # = stringify, ## = token paste. File handling: fopen, fclose, fprintf, fscanf, fread, fwrite, fseek. File modes: r, w, a, r+, w+, a+. Sequential vs Random access.",
  hint:"C syllabus ends here. POLL folder has extra sets for Day14–Day18 — bonus practice. Macro pitfall: #define SQUARE(x) x*x → SQUARE(3+1) = 3+1*3+1 = 7, not 16! Correct: #define SQUARE(x) ((x)*(x))."},
 {id:"w3d4",dow:"Thu",date:"2026-10-01",subject:"DS",topic:"Complexity (best/avg/worst) + sorting intro",
  folder:"sunbeam data structure/DataStructure/Day01",
  pdf:["Day1.pdf"],
  codeDir:"codes",
  extraDir:"diagrams",
  mcq:["../MCQ/Day01_MCQ.pdf"],poll:["../Poll_Questions/Day01_POll_Questions.pdf"],
  note:"C-CAT Section B gives 6-7 DS questions. Topics: Time Complexity (Best/Average/Worst case). Big-O notation: O(1) < O(log n) < O(n) < O(n log n) < O(n²) < O(2ⁿ). Divide & Conquer, Greedy algorithms basics. Sorting: Selection, Bubble, Insertion, Merge, Quick Sort — har ka best/avg/worst case yaad karo.",
  hint:"Open Time_Space_Complexity.xlsx — memorizing this makes the whole DS section much easier. Sorting comparison table banao: Bubble O(n²), Quick O(n log n) avg, Merge O(n log n) guaranteed. Searching: Binary O(log n) — sorted array chahiye, Linear O(n)."},
 {id:"w3d5",dow:"Fri",date:"2026-10-02",subject:"DS",topic:"Sorting: selection, bubble, insertion",
  folder:"sunbeam data structure/DataStructure/Day02",
  pdf:["Day2_1.pdf","Day2_2.pdf"],
  extraDir:"diagrams",
  mcq:["../MCQ/Day02_MCQ.pdf"],poll:["../Poll_Questions/Day02_POll_Questions.pdf"],
  note:"Selection Sort: minimum dhundhke swap — O(n²) always. Bubble Sort: adjacent compare & swap — O(n²) avg, O(n) best (already sorted). Insertion Sort: element ko sahi jagah insert — O(n²) avg, O(n) best. Stability: Bubble & Insertion stable, Selection unstable.",
  hint:"Sorting algorithms ka dry run karo — 5 elements ka array leke step-by-step trace karo. Exam mein puchte hain: Which sorting is stable? Which is in-place? Quick sort = divide & conquer, Merge sort = divide & conquer + stable."},
 {id:"w3d6",dow:"Sat",date:"2026-10-03",subject:"Aptitude",topic:"Aptitude Day 3 + poll questions",
  folder:"suneam apptitude/Aptitude/Day_03",
  note:"Quant focus: Time & Work, Time & Distance, Boats & Streams, Trains. Key formulas: Work = Rate x Time. If A takes x days and B takes y days, together = xy/(x+y) days. Speed = Distance/Time. Relative speed: same direction = subtract, opposite = add.",
  tasks:[
   {label:"Read Apti_Day03.pdf",detail:"suneam apptitude/Aptitude/Day_03/Apti_Day03.pdf"},
   {label:"Solve Aptitude MCQs + Poll Day03",detail:"suneam apptitude/Aptitude/MCQs/Day03_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day03_POll_Questions.pdf"},
   {label:"Re-solve Week 1–3 C POLL questions",dir:"C_Programming_ClassWork/CProgramming/POLL"},
   {label:"Solve all Day01–Day15 from C MCQ sheet",dir:"C_Programming_ClassWork/CProgramming/MCQ"}]},
 {id:"w3d7",dow:"Sun",date:"2026-10-04",subject:"Revision",topic:"Rest",folder:null,
  tasks:[   {label:"Rest. Optionally revise the sorting complexities table"}]}]},

{week:4,title:"Data Structures + C++ start",range:"Mon 5 Oct → Sun 11 Oct",days:[
 {id:"w4d1",dow:"Mon",date:"2026-10-05",subject:"DS",topic:"Merge sort, quick sort, binary/linear search",
  folder:"sunbeam data structure/DataStructure/Day03",
  pdf:[],
  extraDir:"diagrams",
  mcq:["../MCQ/Day03_MCQ.pdf"],poll:["../Poll_Questions/Day03_POll_Questions.pdf"],
  note:"Merge Sort: divide array in half, recursively sort, then merge — O(n log n) guaranteed, stable, O(n) extra space. Quick Sort: pivot choose karo, partition karo — O(n log n) avg, O(n²) worst (already sorted), unstable, in-place. Binary Search: sorted array mein O(log n), mid = (low+high)/2. Linear Search: O(n), unsorted array.",
  hint:"DS Day03 has no lecture PDF — only linked-list diagrams. Cover Merge/Quick sort notes from Day02/Day05 PDFs + YouTube. Binary Search mein overflow bachao: mid = low + (high-low)/2, not (low+high)/2. Merge sort = interview favourite."},
 {id:"w4d2",dow:"Tue",date:"2026-10-06",subject:"DS",topic:"Stack + queue (types, applications, expression conversion)",
  folder:"sunbeam data structure/DataStructure/Day04",
  pdf:[],
  extraDir:"diagrams",
  mcq:["../MCQ/Day04_MCQ.pdf"],poll:["../Poll_Questions/Day04_POll_Questions.pdf"],
  note:"Stack: LIFO — push, pop, peek/top, isEmpty. Applications: Function call stack, Undo/Redo, Expression evaluation, Backtracking. Queue: FIFO — enqueue, dequeue. Types: Simple, Circular, Priority, Deque (Double-ended). Expression: Infix (A+B), Prefix (Post-order), Postfix (In-order). Stack se Infix→Postfix conversion — exam favourite.",
  hint:"This folder also has only diagrams. Practice Infix→Postfix conversion on your own — that's what comes in the exam. Infix → Postfix: operator precedence yaad karo ((), ^, */%, +-). Postfix evaluation: stack use karo — operand push, operator pe pop 2 & push result. Balanced parentheses: stack push '(' and pop on ')'."},
 {id:"w4d3",dow:"Wed",date:"2026-10-07",subject:"DS",topic:"Linked lists, trees, graphs",
  folder:"sunbeam data structure/DataStructure/Day05",
  pdf:["Trees.pdf","HashTable.pdf","graph.pdf"],
  extraDir:"diagrams",
  mcq:["../MCQ/Day05_MCQ.pdf"],poll:["../Poll_Questions/Day05_POll_Questions.pdf"],
  note:"Linked List: Singly (next), Doubly (prev+next), Circular (last→first). Operations: Insert, Delete, Search — O(n). Tree: Terminologies (root, leaf, height, depth, degree). Types: Binary Tree, Binary Search Tree (BST), AVL Tree, Spanning Tree. Traversals: Inorder (Left-Root-Left), Preorder (Root-Left-Right), Postorder (Left-Right-Root). Graph: Basic terminologies (vertex, edge, directed/undirected, weighted).",
  hint:"BST property: left < root < right — Inorder traversal gives sorted order. AVL Tree = self-balancing BST. Spanning Tree: connects all vertices with minimum edges (no cycles). Graph representation: Adjacency Matrix vs Adjacency List — exam mein compare puchte hain."},
 {id:"w4d4",dow:"Thu",date:"2026-10-08",subject:"CPP",topic:"C++ basics: cin/cout, class/object, struct vs class",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day1/CPP_day1",
  pdf:["PD_CPP-DAY1.pdf","Class_board.pdf"],
  codeDir:".",codeFilter:"demo",
  mcq:["../../CPP_day2/CPP_day2/Day01_MCQ.pdf"],
  note:"C-CAT Section B gives 8-9 OOP/C++ questions. Topics: Difference between C struct and C++ class, POP vs OOP. Class = data + methods, Object = instance of class. Access specifiers: private (default), public, protected. cin/cout with >> and << operators. Inspectors (getters), Mutators (setters), Facilitators.",
  hint:"First assignment: write the same employee struct in both .c and .cpp — see the difference yourself. C struct mein data aur functions alag hote hain, C++ class mein saath hota hai. Default access specifier: struct = public, class = private."},
 {id:"w4d5",dow:"Fri",date:"2026-10-09",subject:"CPP",topic:"Constructors, destructors, inline, default args",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day2/CPP_day2",
  pdf:["PD_CPP-DAY2.pdf","Class-Board_OC21.pdf"],
  codeDir:".",codeFilter:"demo",
  mcq:["Day02_MCQ.pdf"],poll:["Day02_POll_Questions.pdf","Day03_POll_Questions.pdf"],
  note:"Constructor: same name as class, no return type, automatic call on object creation. Types: Default, Parameterized, Copy Constructor. Destructor: ~ClassName(), reverse order mein call hota hai, memory free karta hai. Inline function: compiler call ko body se replace karta hai (small functions ke liye). Default arguments: rightmost se start karo.",
  hint:"Complete Assignment_2.txt. Constructor overloading: multiple constructors with different params. Copy constructor: Class(const Class &obj) — shallow copy vs deep copy. Destructor mein cleanup karo (dynamic memory free). Initialization list: ClassName() : x(0), y(0) {} — efficient way."},
 {id:"w4d6",dow:"Sat",date:"2026-10-10",subject:"Aptitude",topic:"Aptitude Day 4 + DS quiz",
  folder:"suneam apptitude/Aptitude/Day_04",
  note:"Quant focus: Simple & Compound Interest, Permutation & Combination, Probability. P&C: nPr = n!/(n-r)!, nCr = n!/(r!(n-r)!). Probability = Favorable/Total outcomes. Calendar & Clock problems: odd days concept, angle between hands formula.",
  tasks:[
   {label:"Read Apti_Day04.pdf",detail:"suneam apptitude/Aptitude/Day_04/Apti_Day04.pdf"},
   {label:"Aptitude MCQs + Poll Day04",detail:"suneam apptitude/Aptitude/MCQs/Day04_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day04_POll_Questions.pdf"},
   {label:"Re-solve all DS MCQs",dir:"sunbeam data structure/DataStructure/MCQ"},
   {label:"Re-solve all DS Poll questions",dir:"sunbeam data structure/DataStructure/Poll_Questions"}]},
 {id:"w4d7",dow:"Sun",date:"2026-10-11",subject:"Revision",topic:"Rest + DS revise",folder:null,
  tasks:[   {label:"Revise sorting complexities table (Time_Space_Complexity.xlsx)"}]}]},

{week:5,title:"C++ finish + OS start",range:"Mon 12 Oct → Sun 18 Oct",days:[
 {id:"w5d1",dow:"Mon",date:"2026-10-12",subject:"CPP",topic:"new/delete, references, static members, friend",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day3/CPP_day3",
  pdf:["PD_CPP-DAY3.pdf","Class_board.pdf"],
  codeDir:".",codeFilter:"demo",
  note:"new/delete: dynamic memory allocation (C++ version of malloc/free). int *p = new int(5); delete p; int *arr = new int[10]; delete[] arr;. Reference variable: int &r = x; — alias hai, memory share karta hai. Static members: shared across all objects. Friend function: class ke private members access kar sakta hai but encapsulation break karta hai. Exception handling: try, catch, throw.",
  hint:"Complete Assignment_2.txt (Day3 version). Reference vs Pointer: reference = no NULL, no reseating, always valid. Pointer = NULL possible, reseat kar sakte ho. Static data member: class ke bahar initialize karo (int MyClass::count = 0). Friend class: entire class gets access."},
 {id:"w5d2",dow:"Tue",date:"2026-10-13",subject:"CPP",topic:"Function/operator overloading, copy constructor",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day4/CPP_day4",
  pdf:["PD_CPP-DAY4.pdf","Class_board.pdf"],
  img:["Shallow-Deep-copy.png"],
  codeDir:".",codeFilter:"demo",
  mcq:["MCQ_OPPS/Day01_MCQ.pdf","MCQ_OPPS/Day02_MCQ.pdf","MCQ_OPPS/Day03_MCQ.pdf","MCQ_OPPS/Day04_MCQ.pdf"],
  poll:["Poll_OOPS/Day01_POll_Questions.pdf","Poll_OOPS/Day02_POll_Questions.pdf"],
  note:"Function Overloading: same name, different parameters (signature matters, not return type). Operator Overloading: + operator ko custom class ke liye define karo (Complex class mein + override). Copy Constructor: shallow copy (default — pointer same address point karega) vs deep copy (custom — alag memory allocate). Assignment operator (=) overload karo for deep copy.",
  hint:"Complete Assignment_4.txt. Make sure to review the Shallow vs Deep copy diagram. Shallow copy mein dono objects ka pointer ek hi memory point karta hai — ek delete karega toh dusra dangling. Deep copy mein alag memory allocate hoti hai — safe hai."},
 {id:"w5d3",dow:"Wed",date:"2026-10-14",subject:"CPP",topic:"Inheritance, virtual functions, templates",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day5/CPP_day5",
  pdf:["../../PD_CPP-DAY5.pdf","Class-Board_OC21.pdf"],
  codeDir:".",codeFilter:"demo",
  mcq:["../../CPP_day4/CPP_day4/MCQ_OPPS/Day05_MCQ.pdf","../../CPP_day4/CPP_day4/MCQ_OPPS/Day06_MCQ.pdf","../../CPP_day4/CPP_day4/MCQ_OPPS/Day07_MCQ.pdf"],
  poll:["../../CPP_day4/CPP_day4/Poll_OOPS/Day03_POll_Questions.pdf"],
  note:"Inheritance: code reusability. Types: Single, Multiple, Multilevel, Hierarchical, Hybrid. Modes: public, private, protected inheritance. Virtual Functions: runtime polymorphism. Pure Virtual Function: = 0 → Abstract class. Virtual Inheritance: diamond problem solve karta hai. Template: generic programming — template<typename T> class/function banao.",
  hint:"Solve Assignment_5.txt (Artist/Painter/Singer inheritance). PD_CPP-DAY5.pdf is one level up (in ObjectOrientedProgramming/), not in the CPP_day5/ folder. Inheritance modes table banao: Base class members kaise inherit honge. Virtual destructor: base class ka destructor virtual hona chahiye agar base pointer se derived delete karna ho."},
 {id:"w5d4",dow:"Thu",date:"2026-10-15",subject:"OS",topic:"OS intro, hardware, memory tech, booting",
  folder:"sunbeam os and cf/CF-OS/day1",
  pdf:["Day-1.pdf","classwork.pdf"],
  mcq:["../day2/Day01_MCQ.pdf"],poll:["../day2/Day01_POll_Questions.pdf"],
  note:"C-CAT Section B gives 8-9 OS questions. Topics: What is OS, types (Batch, Time-sharing, Real-time, Distributed). Booting process: BIOS → POST → MBR → OS load. Memory hierarchy: Register > Cache > RAM > Secondary. RAM types: SRAM (fast, expensive), DRAM (refresh), SDRAM, DDR SDRAM. ROM types: PROM, EPROM, EEPROM, Flash. I/O techniques: Programmed, Interrupt-driven, DMA.",
  hint:"Computer Fundamentals is also in this PDF — Section A's Computer Fundamentals part is covered here. Memory hierarchy yaad karo: speed decreases, size increases, cost per byte decreases as you go down. Cache memory = fastest, SRAM based."},
 {id:"w5d5",dow:"Fri",date:"2026-10-16",subject:"OS",topic:"System calls, dual mode, process & PCB, states",
  folder:"sunbeam os and cf/CF-OS/day2",
  pdf:["Day-2.pdf","classwork.pdf"],
  mcq:["Day01_MCQ.pdf"],poll:["Day01_POll_Questions.pdf"],
  note:"Dual Mode: User Mode (user programs) vs Kernel Mode (OS privileged). System Calls: bridge between user and kernel space (fork, exec, wait, exit, read, write). Process: program in execution. PCB (Process Control Block): process ka data store — PID, state, PC, registers, memory info. Process States: New → Ready → Running → Waiting → Terminated. Context switch: process ka state save/restore.",
  hint:"Memorize the process state diagram — this is guaranteed to appear in the exam. 5 states: New, Ready, Running, Waiting, Terminated. System calls: fork() = new process, exec() = program load, wait() = parent wait for child, exit() = terminate. Dual mode prevents user programs from accessing hardware directly."},
 {id:"w5d6",dow:"Sat",date:"2026-10-17",subject:"Aptitude",topic:"Aptitude Day 5 + C/C++ MCQ revise",
  folder:"suneam apptitude/Aptitude/Day_05",
  note:"Reasoning focus: Seating Arrangement (circular + linear), Blood Relations, Direction Sense. Tips: Circular table = always anticlockwise numbering. Blood relation: draw family tree. Direction: draw compass and mark each step. Number Series: identify pattern (arithmetic, geometric, Fibonacci).",
  tasks:[
   {label:"Read Apti_Day05.pdf",detail:"suneam apptitude/Aptitude/Day_05/Apti_Day05.pdf"},
   {label:"Aptitude MCQs + Poll Day05",detail:"suneam apptitude/Aptitude/MCQs/Day05_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day05_POll_Questions.pdf"},
   {label:"Solve all C MCQ + POLL PDFs",dirs:["C_Programming_ClassWork/CProgramming/MCQ","C_Programming_ClassWork/CProgramming/POLL"]},
   {label:"Solve all C++ output questions from Code_MCQ.txt",detail:"sunbeam cpp/ObjectOrientedProgramming/CPP_day5/CPP_day5/Code_MCQ.txt"}]},
 {id:"w5d7",dow:"Sun",date:"2026-10-18",subject:"Revision",topic:"Rest + C++ revise",folder:null,
  tasks:[   {label:"Revise inheritance modes table (public/private/protected)"}]}]},

{week:6,title:"OS finish + Networking",range:"Mon 19 Oct → Sun 25 Oct",days:[
 {id:"w6d1",dow:"Mon",date:"2026-10-19",subject:"OS",topic:"CPU scheduling algorithms, IPC, sync",
  folder:"sunbeam os and cf/CF-OS/day3",
  pdf:["Day-3.pdf","classwork.pdf"],
  mcq:["Day02_MCQ.pdf"],poll:["Day02_POll_Questions.pdf"],
  note:"CPU Scheduling Algorithms: FCFS (first come first served, convoy effect), SJF (shortest job first, optimal avg waiting), Priority (priority based, starvation possible), Round Robin (time quantum based, fair). Preemptive vs Non-preemptive. IPC (Inter-Process Communication): Shared Memory, Message Passing. Synchronization: Race condition, Critical section problem. Solutions: Peterson's algorithm, Semaphores (binary & counting).",
  hint:"Solve FCFS/SJF/RR numericals by hand — memorizing formulas alone won't work. Waiting time = Turnaround time - Burst time. Turnaround time = Completion time - Arrival time. RR mein time quantum kam ho toh context switches badhenge, zyada ho toh FCFS jaisa ho jayega."},
 {id:"w6d2",dow:"Tue",date:"2026-10-20",subject:"OS",topic:"Deadlocks + handling",
  folder:"sunbeam os and cf/CF-OS/day4",
  pdf:["Day-4.pdf","classwork.pdf"],
  extra:["Semaphore.txt"],
  mcq:["Day03_MCQ.pdf"],poll:["Day03_POll_Questions.pdf"],
  note:"Deadlock: 4 conditions (Coffman): Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait — sab hona chahiye. Handling: Prevention (kisi ek condition ko break), Avoidance (Banker's algorithm — safe state check), Detection + Recovery. Banker's algorithm: Available, Max, Allocation, Need matrix. Safe sequence dhundho.",
  hint:"4 necessary conditions of deadlock + Banker's algorithm. Deadlock prevention mein circular wait break karo — resources ko order mein assign karo. Banker's algorithm numerical practice karo: Need = Max - Allocation, then check if Need ≤ Available for any process. Semaphore = integer variable, wait() decrements, signal() increments."},
 {id:"w6d3",dow:"Wed",date:"2026-10-21",subject:"OS",topic:"Memory mgmt: paging, segmentation, virtual memory",
  folder:"sunbeam os and cf/CF-OS/day5",
  pdf:["Day-5.pdf","Classwork1.pdf","Classwork2.pdf"],
  extra:["page_R_algo.pdf"],
  mcq:["Day04_MCQ.pdf"],poll:["Day04_POll_Questions.pdf"],
  note:"Memory Management: Contiguous allocation (first fit, best fit, worst fit). Paging: process ko fixed-size pages mein divide, memory ko frames mein — logical to physical mapping via page table. Segmentation: variable-size segments (logical division). Virtual Memory: process ka address space > physical memory. Demand Paging: page tab aaye load karo. Page Fault: page memory mein nahi hai. Thrashing: page faults bahut zyada.",
  hint:"Solve one worked example for each page replacement algorithm (FIFO/LRU/Optimal). Page replacement: FIFO (first in out), LRU (least recently used — best practical), Optimal (theoretical best). TLB (Translation Lookaside Buffer) = page table cache. Internal fragmentation = paging, External fragmentation = segmentation."},
 {id:"w6d4",dow:"Thu",date:"2026-10-22",subject:"OS",topic:"File systems, disk scheduling",
  folder:"sunbeam os and cf/CF-OS/day6",
  pdf:["Day-6_1.pdf","disk algo.pdf"],
  mcq:["OS_POLL_MCQ_2026/MCQ_OS/Day01_MCQ.pdf","OS_POLL_MCQ_2026/MCQ_OS/Day02_MCQ.pdf","OS_POLL_MCQ_2026/MCQ_OS/Day03_MCQ.pdf"],
  poll:["OS_POLL_MCQ_2026/Poll_OS/Day01_POll_Questions.pdf","OS_POLL_MCQ_2026/Poll_OS/Day02_POll_Questions.pdf"],
  note:"File System: file ka organization. File Allocation Methods: Contiguous (fast, external frag), Linked (no frag, slow random access), Indexed (inode-based, UNIX). Disk Scheduling: FCFS (simple), SSTF (shortest seek — starvation), SCAN (elevator — bidirectional), C-SCAN (circular, one direction only). Seek time, Rotational latency, Transfer time = Disk access time.",
  hint:"FCFS/SSTF/SCAN/C-SCAN seek-time calculations. Disk scheduling numerical practice karo: head position diya hai, requests diye hain — total head movement calculate karo. SCAN mein direction change hota hai, C-SCAN mein wapas start pe jaata hai. File descriptor: file handle jo OS deta hai."},
 {id:"w6d5",dow:"Fri",date:"2026-10-23",subject:"DCN",topic:"Network types, transmission media, OSI model layers",
  folder:"sunbeam dcn/DCN/Day_01",
  pdf:["DCN_Day01.pdf","Day01_Notes.pdf"],
  mcq:["../MCQs/Day01_MCQ.pdf"],poll:["../Poll_Questions/Day01_POll_Questions.pdf"],
  note:"C-CAT gives 4-5 DCN questions in Section B. Topics: Transmission Media (Twisted pair, Coaxial, Fiber optic, Wireless), Switching (Circuit, Message, Packet), Multiplexing (FDM, TDM, WDM). Network Types: LAN, MAN, WAN, WLAN, SAN, CAN. LAN technologies: Token Ring vs Ethernet, MAC address format.",
  hint:"OSI 7 layers + protocols for each layer — this just has to be memorized. Make a table: Layer Name | PDU | Protocol Example | Device. exam mein har layer ka kaam puchte hain."},
 {id:"w6d6",dow:"Sat",date:"2026-10-24",subject:"Aptitude",topic:"Aptitude Day 6 (English) + DCN MCQs",
  folder:"suneam apptitude/Aptitude/Day_06",
  note:"English focus: Reading Comprehension (read passage carefully, answers are IN the passage), Prepositions (of, by, on, at, with — common errors), Articles (A/An/The rules), Synonyms & Antonyms (build vocabulary daily), Idioms & Phrases (learn 2-3 daily), Active/Passive Voice, Sentence Arrangement (PQRS format).",
  tasks:[
   {label:"Read Apti_Day06.pdf and Apti_Day06_English.pdf",detail:"suneam apptitude/Aptitude/Day_06/Apti_Day06.pdf\nsuneam apptitude/Aptitude/Day_06/Apti_Day06_English.pdf"},
   {label:"Solve DCN_MCQs.pdf",detail:"sunbeam dcn/DCN/Day_03/DCN_MCQs.pdf"},
   {label:"Revise one topic from English_Data",dir:"suneam apptitude/Aptitude/English_Data"}]},
 {id:"w6d7",dow:"Sun",date:"2026-10-25",subject:"Revision",topic:"Rest + OS revise",folder:null,
  tasks:[   {label:"Revise CPU scheduling + deadlock conditions"}]}]},

{week:7,title:"Networking finish + Big Data",range:"Mon 26 Oct → Sun 1 Nov",days:[
 {id:"w7d1",dow:"Mon",date:"2026-10-26",subject:"DCN",topic:"IP addressing, TCP/IP protocols (ARP, ICMP, TCP, UDP, DNS, HTTP)",
  folder:"sunbeam dcn/DCN/Day_02",
  pdf:["DCN_Day02.pdf","Day02_Notes.pdf"],
  mcq:["../MCQs/Day02_MCQ.pdf"],poll:["../Poll_Questions/Day02_POll_Questions.pdf"],
  note:"IP Addressing: Classful (A/B/C/D/E) me subnet mask yaad karo. Classless (CIDR) — /24, /16 kya hota hai. IPv6: 128-bit address, why needed (IPv4 exhaustion). Port Numbers: FTP=21, Telnet=23, SMTP=25, DNS=53, HTTP=80, HTTPS=443.",
  hint:"TCP vs UDP table banao: Connection-oriented vs Connectionless, Reliable vs Unreliable, Header size (20B vs 8B), Use cases. ARP ka kaam yaad karo: IP → MAC mapping. ICMP ping use karta hai. DNS = domain name → IP."},
 {id:"w7d2",dow:"Tue",date:"2026-10-27",subject:"DCN",topic:"DCN wrap-up: network devices, protocols revision + MCQs",
  folder:"sunbeam dcn/DCN/Day_03",
  pdf:["DCN_Day03.pdf","Day03_Notes.pdf","DCN_MCQs.pdf"],
  img:["diag.png"],
  mcq:["../MCQs/Day03_MCQ.pdf"],poll:["../Poll_Questions/Day03_POll_Questions.pdf"],
  note:"Network Devices: Hub (Layer 1, broadcast), Switch (Layer 2, MAC-based), Router (Layer 3, IP-based), Bridge (connects 2 LANs). Server-client vs Cloud computing basics. OSI vs TCP/IP comparison: OSI 7 layers, TCP/IP 4 layers. Protocols: ARP, IP, ICMP, TCP, UDP, FTP, Telnet, DNS, HTTP — har ek ka kaam 1 line me likho.",
  hint:"DCN se 4-5 questions aayenge Section B me. examiner ko protocol numbers yaad hain — TCP=6, UDP=17, ICMP=1. OSI layers ke devices puchte hain: Hub=Physical, Switch=Data Link, Router=Network. Switching techniques bhi puchte hain: Circuit vs Packet switching."},
 {id:"w7d3",dow:"Wed",date:"2026-10-28",subject:"BigData",topic:"Big Data: 5 V's, types of data, batch vs streaming",
  folder:"sunbeam bigdata/BigData/day1",
  pdf:["DataEngg-Day1.pdf"],
  mcq:["Day01_MCQ.pdf"],poll:["Day01_POll_Questions.pdf"],
  note:"C-CAT Section B gives 5-6 Big Data questions. 5 V's: Volume (size), Velocity (speed), Variety (types), Veracity (quality), Value (usefulness). Data types: Structured (tables), Semi-structured (JSON, XML), Unstructured (images, videos). Processing: Batch (Hadoop MapReduce — offline, large datasets), Stream (real-time — Spark Streaming, Kafka). Hadoop Ecosystem: HDFS (storage), MapReduce (processing), YARN (resource management).",
  hint:"5 V's yaad karo — exam mein directly puchte hain. Batch vs Streaming: Batch = high latency, high throughput (e.g. daily report). Stream = low latency, real-time (e.g. live dashboard). Hadoop = commodity hardware pe large data process. MapReduce = Map (filter) + Reduce (aggregate)."},
 {id:"w7d4",dow:"Thu",date:"2026-10-29",subject:"BigData",topic:"RDBMS/SQL vs NoSQL, CAP, ETL vs ELT, OLAP vs OLTP",
  folder:"sunbeam bigdata/BigData/day2",
  pdf:["DataEngg-day2.pdf"],
  mcq:["Day02_MCQ.pdf"],poll:["Day02_POll_Questions.pdf"],
  note:"RDBMS vs NoSQL: SQL = structured, ACID, schema-fixed. NoSQL = flexible schema, BASE, horizontal scaling. CAP Theorem: Consistency + Availability + Partition Tolerance — sirf 2 mil sakte hain. ACID (Atomicity, Consistency, Isolation, Durability) vs BASE (Basically Available, Soft state, Eventually consistent). ETL vs ELT: Transform step ka order different. OLTP (real-time transactions) vs OLAP (analytics, data warehouse).",
  hint:"ACID vs BASE + CAP theorem — only 3 short topics, don't spend too much time. CAP theorem mein: CP system = MongoDB, AP system = Cassandra. NoSQL types: Document (MongoDB), Key-Value (Redis), Column-family (Cassandra), Graph (Neo4j). OLTP = day-to-day operations, OLAP = reporting & analysis."},
 {id:"w7d5",dow:"Fri",date:"2026-10-30",subject:"BigData",topic:"Hadoop, Hive, Spark intro, careers",
  folder:"sunbeam bigdata/BigData/day3",
  pdf:["DataEngg-Day3.pdf"],
  mcq:["Day03_MCQ.pdf"],poll:["Day03_POll_Questions.pdf"],
  note:"Hadoop ecosystem deep dive: HDFS (NameNode + DataNodes, 128MB blocks, replication factor 3), MapReduce (Map → Shuffle → Reduce). Hive: SQL-like interface on Hadoop (HiveQL). Spark: in-memory processing, 100x faster than MapReduce, supports batch + stream. Spark components: Spark SQL, Spark Streaming, MLlib (ML), GraphX. NoSQL databases: MongoDB (document), Cassandra (column), Redis (key-value).",
  hint:"Hadoop vs Spark: Hadoop = disk-based, slow but fault-tolerant. Spark = memory-based, fast but needs more RAM. HDFS: data locality principle — compute near data, not data near compute. Careers: Data Engineer, Data Analyst, Data Scientist, Big Data Architect. Big Data tools yaad karo: Hadoop, Spark, Kafka, Hive, Pig, HBase, Sqoop, Flume."},
 {id:"w7d6",dow:"Sat",date:"2026-10-31",subject:"Aptitude",topic:"Aptitude Day 7 (Reasoning) + BigData MCQs",
  folder:"suneam apptitude/Aptitude/Day_07",
  note:"Reasoning focus: Syllogism (All A are B, Some B are C → conclusion), Coding-Decoding (A=1, B=2 pattern), Coded Inequality (relationship between symbols), Puzzle Test (multi-variable logic), Data Sufficiency (do you have enough info?). Tips: For syllogism, draw Venn diagrams. For coding, check pattern shift.",
  tasks:[
   {label:"Read Apti_Day07_Reasoning.pdf",detail:"suneam apptitude/Aptitude/Day_07/Apti_Day07_Reasoning.pdf"},
   {label:"Solve all BigData MCQs + Polls",dirs:["sunbeam bigdata/BigData/day1","sunbeam bigdata/BigData/day2","sunbeam bigdata/BigData/day3"]},
   {label:"Practice one chapter from RS Aggarwal Reasoning",detail:"suneam apptitude/Aptitude/RS Aggarwal reasoning .pdf"}]},
 {id:"w7d7",dow:"Sun",date:"2026-11-01",subject:"Revision",topic:"Rest + DCN skim",folder:null,
  tasks:[   {label:"Skim DCN notes"}]}]},

{week:8,title:"AI + Full Revision + Mocks",range:"Mon 2 Nov → Sun 8 Nov",days:[
 {id:"w8d1",dow:"Mon",date:"2026-11-02",subject:"AI",topic:"AI: agents, types of AI, ML vs DL basics",
  folder:"sun/Artificial-Intelligence/Day_01",
  pdf:["AI_Day01.pdf","AI_Day01_notes.pdf"],
  mcq:["../MCQs/Day01_MCQ.pdf"],poll:["../Poll_Questions/Day01_POll_Questions.pdf"],
  note:"C-CAT Section B gives 5-6 AI questions. AI = simulating human intelligence. Types: Narrow AI (task-specific, e.g. Siri), General AI (human-level), Super AI (beyond human). AI Agents: Reactive, Limited Memory, Theory of Mind, Self-aware. ML = subset of AI (learning from data). DL = subset of ML (neural networks with many layers). ML types: Supervised (labeled data), Unsupervised (no labels), Reinforcement (reward-based).",
  hint:"AI vs ML vs DL: AI > ML > DL (subset relationship). Supervised learning examples: Classification (spam/not spam), Regression (price prediction). Unsupervised: Clustering (K-means), Association (Apriori). Neural Network: Input → Hidden → Output layers, weights update via backpropagation."},
 {id:"w8d2",dow:"Tue",date:"2026-11-03",subject:"AI",topic:"Neural networks, fuzzy logic, trends",
  folder:"sun/Artificial-Intelligence/Day_02",
  pdf:["AI_Day02.pdf","AI_Day02_notes.pdf"],
  extra:["AI_MCQs.txt  (50 solved questions — revise them)"],
  mcq:["../MCQs/Day02_MCQ.pdf"],poll:["../Poll_Questions/Day02_POll_Questions.pdf"],
  note:"Neural Networks: inspired by brain neurons. Perceptron = single layer. Multi-layer perceptron (MLP) = multiple hidden layers. Activation functions: Sigmoid, ReLU, Tanh. Backpropagation = error propagate karke weights update. Fuzzy Logic: imprecise data handle karta hai (0 to 1 range, not just 0/1). NLP: human language understanding — tokenization, parsing, sentiment analysis. AI trends: Self-driving, Chatbots, Recommendation systems, Computer Vision.",
  hint:"Section B complete! Now enter revision + mock mode. Neural Network: forward pass → calculate loss → backpropagation → update weights. Fuzzy Logic vs Boolean: Boolean = crisp (0/1), Fuzzy = gradual (0.0 to 1.0). NLP components: Tokenization → POS Tagging → Parsing → Semantic Analysis. AI MCQs.txt mein 50 solved questions hain — unhe revise karo."},
 {id:"w8d3",dow:"Wed",date:"2026-11-04",subject:"Revision",topic:"Full revision 1: C + DS",folder:null,
  tasks:[
   {label:"Solve all C MCQ + POLL",dirs:["C_Programming_ClassWork/CProgramming/MCQ","C_Programming_ClassWork/CProgramming/POLL"]},
   {label:"Solve all DS MCQs + Polls",dirs:["sunbeam data structure/DataStructure/MCQ","sunbeam data structure/DataStructure/Poll_Questions"]},
   {label:"Re-solve c quize.txt",detail:"quize pdfs/c quize.txt"}]},
 {id:"w8d4",dow:"Thu",date:"2026-11-05",subject:"Revision",topic:"Full revision 2: C++ + OS + DCN + BigData + AI",folder:null,
  tasks:[
   {label:"Re-solve Code_MCQ.txt",detail:"sunbeam cpp/ObjectOrientedProgramming/CPP_day5/CPP_day5/Code_MCQ.txt"},
   {label:"Solve all CPP MCQs + Polls",dirs:["sunbeam cpp/ObjectOrientedProgramming/CPP_day4/CPP_day4/MCQ_OPPS","sunbeam cpp/ObjectOrientedProgramming/CPP_day4/CPP_day4/Poll_OOPS"]},
   {label:"Solve all OS MCQs + Polls",dirs:["sunbeam os and cf/CF-OS/day2","sunbeam os and cf/CF-OS/day3","sunbeam os and cf/CF-OS/day4","sunbeam os and cf/CF-OS/day5","sunbeam os and cf/CF-OS/day6/OS_POLL_MCQ_2026/MCQ_OS","sunbeam os and cf/CF-OS/day6/OS_POLL_MCQ_2026/Poll_OS"]},
   {label:"Solve DCN + BigData + AI MCQ/Poll sets",dirs:["sunbeam dcn/DCN/MCQs","sunbeam dcn/DCN/Poll_Questions","sunbeam bigdata/BigData/day1","sunbeam bigdata/BigData/day2","sunbeam bigdata/BigData/day3","sun/Artificial-Intelligence/MCQs","sun/Artificial-Intelligence/Poll_Questions"]}]},
 {id:"w8d5",dow:"Fri",date:"2026-11-06",subject:"Mock",topic:"Mock C-CAT #1 (100 Qs, A+B, timed, −1 marking)",
  folder:null,
  tasks:[
   {label:"Section A: 50 Qs — solve with a 1-hour timer"},
   {label:"Section B: 50 Qs — 1 hour"},
   {label:"Enter score in Mock Log tab (+3 / −1 marking)"}]},  {id:"w8d6",dow:"Sat",date:"2026-11-07",subject:"Mock",topic:"Mock #2 + fix every wrong question",
  folder:null,
  tasks:[
   {label:"Take Mock #2 and enter score in Mock Log"},
   {label:"Log whatever you got wrong in the Weak Topics tab"},
   {label:"Understand the reason for each wrong answer — don't just look at the answer"}]},
 {id:"w8d7",dow:"Sun",date:"2026-11-08",subject:"Revision",topic:"Light day: formula sheet + relax",folder:null,
  tasks:[
   {label:"Read formule.txt and notes.txt",dir:"sunbeam practices"},
   {label:"Revise bitwise operator formulas"},
   {label:"Nothing new today — give your brain a rest"}]}]}
];
