import type { Week } from "./types";

/**
 * The 8-week study plan, ported verbatim from Study_Dashboard.html.
 * Every path in here is relative to the vault and resolves against data/manifest.json.
 */
export const PLAN: Week[] = [
{week:1,title:"C Basics",range:"Mon 14 Sep → Sun 20 Sep",days:[
 {id:"w1d1",dow:"Mon",date:"2026-09-14",subject:"C",topic:"What is C, how a program runs, main(), printf, tokens",
  folder:"C_Programming_ClassWork/CProgramming/Day1",
  pdf:["C_Programming_Day1.pdf","C_Programming_Day2.pdf","Diagram_CProg_Day1_Part1.pdf","Diagram_CProgramming_Dat1_Part2.xopp"],
  img:["ASCII.png","ProgramFuncStmt_Token.png"],
  codeDir:"code",
  mcq:["../MCQ/Day01_MCQ.pdf"],poll:["../POLL/Day01_POll_Questions.pdf"],
  hint:"Foundation day. If C is strong, DS + C++ will be easier."},
 {id:"w1d2",dow:"Tue",date:"2026-09-15",subject:"C",topic:"Identifiers, keywords, data types, variables",
  folder:"C_Programming_ClassWork/CProgramming/Day2",
  pdf:["C_Programming_Day1.pdf","C_Programming_Day3.pdf","C_Programming_Day4.pdf","Diagram_Day3_CProg.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day02_MCQ.pdf"],poll:["../POLL/Day02_POll_Questions.pdf"],
  hint:"Folder naming off-by-one: Day2's actual lecture C_Programming_Day2.pdf is in the Day1/ folder."},
 {id:"w1d3",dow:"Wed",date:"2026-09-16",subject:"C",topic:"Operators (priority & associativity)",
  folder:"C_Programming_ClassWork/CProgramming/Day3",
  pdf:["C_Programming_Day4.pdf","Diagrams_CProg_Day3.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day03_MCQ.pdf"],poll:["../POLL/Day03_POll_Questions.pdf"],
  hint:"Day3's lecture C_Programming_Day3.pdf is in the previous folder (Day2/). Diagrams are in the right place."},
 {id:"w1d4",dow:"Thu",date:"2026-09-17",subject:"C",topic:"Control flow: if / else, switch",
  folder:"C_Programming_ClassWork/CProgramming/Day4",
  pdf:["Day5.pdf","Day6.pdf","Diagrams_CProg_Day4_Part1.pdf","Diagrams_CProg_Day4_Part2.pdf"],
  img:["Screenshot 2024-04-12 120112.png","Screenshot 2024-04-12 120146.png","Screenshot 2024-04-12 121529.png","Screenshot 2024-04-12 121554.png","Screenshot 2024-11-18 113419.png","Screenshot 2024-11-18 113542.png","Screenshot 2024-11-18 113606.png","Screenshot 2024-11-18 113637.png"],
  codeDir:"code",
  mcq:["../MCQ/Day04_MCQ.pdf"],poll:["../POLL/Day04_POll_Questions.pdf"],
  hint:"Day4's lecture C_Programming_Day4.pdf is in Day3/ (and Day2/)."},
 {id:"w1d5",dow:"Fri",date:"2026-09-18",subject:"C",topic:"Loops: while, do-while, for",
  folder:"C_Programming_ClassWork/CProgramming/Day5",
  pdf:["Day7.pdf","Day8.pdf","Diagram_CProg_Day5_Part1.pdf","Diagram_CProg_Day5_Part2.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day05_MCQ.pdf"],poll:["../POLL/Day05_POll_Questions.pdf"]},
 {id:"w1d6",dow:"Sat",date:"2026-09-19",subject:"Practice",topic:"Week-1 revision + Aptitude Day 1",
  folder:"suneam apptitude/Aptitude/Day_01",
  tasks:[
   {label:"Rewrite all Week 1 demo .c files from memory and run them",dirs:["C_Programming_ClassWork/CProgramming/Day1/code","C_Programming_ClassWork/CProgramming/Day2/code","C_Programming_ClassWork/CProgramming/Day3/code","C_Programming_ClassWork/CProgramming/Day4/code","C_Programming_ClassWork/CProgramming/Day5/code"]},
   {label:"Read Aptitude Day_01 lecture",detail:"suneam apptitude/Aptitude/Day_01/Apti_Day01.pdf"},
   {label:"Solve Aptitude MCQs + Poll",detail:"suneam apptitude/Aptitude/MCQs/Day01_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day01_POll_Questions.pdf"}]},
 {id:"w1d7",dow:"Sun",date:"2026-09-20",subject:"Revision",topic:"Rest + week revise",
  folder:null,
  tasks:[
   {label:"Skim Week 1 PDFs again"},
   {label:"Re-solve the MCQs you got wrong, without looking at answers"},
   {label:"Log this week's mistakes in the Weak Topics tab"}]}]},

{week:2,title:"C Core",range:"Mon 21 Sep → Sun 27 Sep",days:[
 {id:"w2d1",dow:"Mon",date:"2026-09-21",subject:"C",topic:"Functions, pass by value vs address, recursion",
  folder:"C_Programming_ClassWork/CProgramming/Day6",
  pdf:["Day8.pdf","Day9.pdf","Day10.pdf","Diagrams_CProg_Day6_Part1.pdf","Diagrams_CProg_Day6_Part2.pdf","Diagrams_CProg_Day6_Part3.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day06_MCQ.pdf"],poll:["../POLL/Day06_POll_Questions.pdf"],
  hint:"Pass by value vs address is an exam favourite — write one program with each."},
 {id:"w2d2",dow:"Tue",date:"2026-09-22",subject:"C",topic:"Storage classes, scope",
  folder:"C_Programming_ClassWork/CProgramming/Day7",
  pdf:["Day9.pdf","Day10.pdf","Diagram_CProg_Day7.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day07_MCQ.pdf"],poll:["../POLL/Day07_POll_Questions.pdf"],
  hint:"auto / static / extern / register — output-prediction questions come from here."},
 {id:"w2d3",dow:"Wed",date:"2026-09-23",subject:"C",topic:"Arrays (1D, 2D)",
  folder:"C_Programming_ClassWork/CProgramming/Day8",
  pdf:["Day10.pdf","Diagrams_CProg_Day8.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day08_MCQ.pdf"],poll:["../POLL/Day08_POll_Questions.pdf"]},
 {id:"w2d4",dow:"Thu",date:"2026-09-24",subject:"C",topic:"Strings + library functions",
  folder:"C_Programming_ClassWork/CProgramming/Day9",
  pdf:["Day10.pdf","Day13.pdf","Diagram_CProg_Day9_annotated.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day09_MCQ.pdf"],poll:["../POLL/Day09_POll_Questions.pdf"]},
 {id:"w2d5",dow:"Fri",date:"2026-09-25",subject:"C",topic:"Pointers: wild / NULL / void, pointer arithmetic",
  folder:"C_Programming_ClassWork/CProgramming/Day10",
  pdf:["Day13.pdf","Diagram_CProg_Day10.pdf"],
  mcq:["../MCQ/Day10_MCQ.pdf"],poll:["../POLL/Day10_POll_Questions.pdf"],
  hint:"No code/ folder today — write your own programs. Pointers = highest marks topic."},
 {id:"w2d6",dow:"Sat",date:"2026-09-26",subject:"Practice",topic:"Aptitude Day 2 + ab tak ke quiz",
  folder:"suneam apptitude/Aptitude/Day_02",
  tasks:[
   {label:"Read Apti_Day02.pdf",detail:"suneam apptitude/Aptitude/Day_02/Apti_Day02.pdf"},
   {label:"Solve Apti MCQs + Poll Day02",detail:"suneam apptitude/Aptitude/MCQs/Day02_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day02_POll_Questions.pdf"},
   {label:"Solve output-prediction questions from c quize.txt",detail:"quize pdfs/c quize.txt  (20 questions)"},
   {label:"Solve C questions from Quiz PDFs",detail:"quize pdfs/Quiz_Questions_and_Solutions.pdf"}]},
 {id:"w2d7",dow:"Sun",date:"2026-09-27",subject:"Revision",topic:"Rest + week revise",
  folder:null,
  tasks:[   {label:"Skim Week 2 PDFs"},{label:"Mid-point check: ~70% C syllabus done — test yourself"}]}]},

{week:3,title:"C finishing + Data Structures",range:"Mon 28 Sep → Sun 4 Oct",days:[
 {id:"w3d1",dow:"Mon",date:"2026-09-28",subject:"C",topic:"Pointers + arrays, dynamic memory (malloc/free)",
  folder:"C_Programming_ClassWork/CProgramming/Day11",
  pdf:["Day13.pdf","Day15.pdf","Diagram_CProg_Day11.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day11_MCQ.pdf"],poll:["../POLL/Day11_POll_Questions.pdf"],
  hint:"malloc/free + memory leak questions are guaranteed to appear."},
 {id:"w3d2",dow:"Tue",date:"2026-09-29",subject:"C",topic:"Structures, unions, bit fields",
  folder:"C_Programming_ClassWork/CProgramming/Day12",
  pdf:["Day15_1.pdf","Diagrams_CProg_Day12_Part1.pdf","Diagrams_CProg_Day12_Part2.pdf","Final_Day18.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day12_MCQ.pdf"],poll:["../POLL/Day12_POll_Questions.pdf"],
  hint:"struct vs union size — get into the habit of calculating it."},
 {id:"w3d3",dow:"Wed",date:"2026-09-30",subject:"C",topic:"Preprocessor, file handling",
  folder:"C_Programming_ClassWork/CProgramming/Day13",
  pdf:["Day18.pdf","Diagram_CProg_Day17.pdf"],
  img:["Screenshot 2024-10-17 115041.png"],
  codeDir:"code",
  mcq:["../MCQ/Day13_MCQ.pdf"],poll:["../POLL/Day13_POll_Questions.pdf"],
  hint:"C syllabus ends here. POLL folder has extra sets for Day14–Day18 — bonus practice."},
 {id:"w3d4",dow:"Thu",date:"2026-10-01",subject:"DS",topic:"Complexity (best/avg/worst) + sorting intro",
  folder:"sunbeam data structure/DataStructure/Day01",
  pdf:["Day1.pdf"],
  codeDir:"codes",
  extraDir:"diagrams",
  mcq:["../MCQ/Day01_MCQ.pdf"],poll:["../Poll_Questions/Day01_POll_Questions.pdf"],
  hint:"Open Time_Space_Complexity.xlsx — memorizing this makes the whole DS section much easier."},
 {id:"w3d5",dow:"Fri",date:"2026-10-02",subject:"DS",topic:"Sorting: selection, bubble, insertion",
  folder:"sunbeam data structure/DataStructure/Day02",
  pdf:["Day2_1.pdf","Day2_2.pdf"],
  extraDir:"diagrams",
  mcq:["../MCQ/Day02_MCQ.pdf"],poll:["../Poll_Questions/Day02_POll_Questions.pdf"]},
 {id:"w3d6",dow:"Sat",date:"2026-10-03",subject:"Practice",topic:"Aptitude Day 3 + poll questions",
  folder:"suneam apptitude/Aptitude/Day_03",
  tasks:[
   {label:"Read Apti_Day03.pdf",detail:"suneam apptitude/Aptitude/Day_03/Apti_Day03.pdf"},
   {label:"Solve Aptitude MCQs + Poll Day03",detail:"suneam apptitude/Aptitude/MCQs/Day03_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day03_POll_Questions.pdf"},
   {label:"Re-solve Week 1–3 C POLL questions",dir:"C_Programming_ClassWork/CProgramming/POLL"},
   {label:"Solve all Day01–Day15 from C MCQ sheet",dir:"C_Programming_ClassWork/CProgramming/MCQ"}]},
 {id:"w3d7",dow:"Sun",date:"2026-10-04",subject:"Revision",topic:"Rest",folder:null,
  tasks:[   {label:"Rest. Optionally revise the sorting complexities table"}]}]},

{week:4,title:"Data Structures + C++ start",range:"Mon 5 Oct → Sun 11 Oct",days:[
 {id:"w4d1",dow:"Mon",date:"2026-10-05",subject:"DS",topic:"Merge sort, quick sort, binary/linear search",
  folder:"sunbeam data structure/DataStructure/Day03",
  pdf:[],
  extraDir:"diagrams",
  mcq:["../MCQ/Day03_MCQ.pdf"],poll:["../Poll_Questions/Day03_POll_Questions.pdf"],
  hint:"DS Day03 has no lecture PDF — only linked-list diagrams. Cover Merge/Quick sort notes from Day02/Day05 PDFs + YouTube."},
 {id:"w4d2",dow:"Tue",date:"2026-10-06",subject:"DS",topic:"Stack + queue (types, applications, expression conversion)",
  folder:"sunbeam data structure/DataStructure/Day04",
  pdf:[],
  extraDir:"diagrams",
  mcq:["../MCQ/Day04_MCQ.pdf"],poll:["../Poll_Questions/Day04_POll_Questions.pdf"],
  hint:"This folder also has only diagrams. Practice Infix→Postfix conversion on your own — that's what comes in the exam."},
 {id:"w4d3",dow:"Wed",date:"2026-10-07",subject:"DS",topic:"Linked lists, trees, graphs",
  folder:"sunbeam data structure/DataStructure/Day05",
  pdf:["Trees.pdf","HashTable.pdf","graph.pdf"],
  extraDir:"diagrams",
  mcq:["../MCQ/Day05_MCQ.pdf"],poll:["../Poll_Questions/Day05_POll_Questions.pdf"]},
 {id:"w4d4",dow:"Thu",date:"2026-10-08",subject:"CPP",topic:"C++ basics: cin/cout, class/object, struct vs class",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day1/CPP_day1",
  pdf:["PD_CPP-DAY1.pdf","Class_board.pdf"],
  codeDir:".",codeFilter:"demo",
  mcq:["../../CPP_day2/CPP_day2/Day01_MCQ.pdf"],
  note:"Assignment_1.txt has 5 programs — write all of them.",
  hint:"First assignment: write the same employee struct in both .c and .cpp — see the difference yourself."},
 {id:"w4d5",dow:"Fri",date:"2026-10-09",subject:"CPP",topic:"Constructors, destructors, inline, default args",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day2/CPP_day2",
  pdf:["PD_CPP-DAY2.pdf","Class-Board_OC21.pdf"],
  codeDir:".",codeFilter:"demo",
  mcq:["Day02_MCQ.pdf"],poll:["Day02_POll_Questions.pdf","Day03_POll_Questions.pdf"],
  note:"Complete Assignment_2.txt."},
 {id:"w4d6",dow:"Sat",date:"2026-10-10",subject:"Practice",topic:"Aptitude Day 4 + DS quiz",
  folder:"suneam apptitude/Aptitude/Day_04",
  tasks:[
   {label:"Read Apti_Day04.pdf",detail:"suneam apptitude/Aptitude/Day_04/Apti_Day04.pdf"},
   {label:"Aptitude MCQs + Poll Day04",detail:"suneam apptitude/Aptitude/MCQs/Day04_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day04_POll_Questions.pdf"},
   {label:"Re-solve all DS MCQs",dir:"sunbeam data structure/DataStructure/MCQ"},
   {label:"Re-solve all DS Poll questions",dir:"sunbeam data structure/DataStructure/Poll_Questions"}]},
 {id:"w4d7",dow:"Sun",date:"2026-10-11",subject:"Revision",topic:"Rest + DS revise",folder:null,
  tasks:[   {label:"Revise sorting complexities table (Time_Space_Complexity.xlsx)"}]}]},

{week:5,title:"C++ finish + OS start",range:"Mon 12 Oct → Sun 18 Oct",days:[
 {id:"w5d1",dow:"Mon",date:"2026-10-12",subject:"CPP",topic:"new/delete, references, static members, friend",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day3/CPP_day3",
  pdf:["PD_CPP-DAY3.pdf","Class_board.pdf"],
  codeDir:".",codeFilter:"demo",
  note:"Complete Assignment_2.txt (Day3 version).",
  hint:"Reference variable + static = most questions in Code_MCQ.txt come from these topics."},
 {id:"w5d2",dow:"Tue",date:"2026-10-13",subject:"CPP",topic:"Function/operator overloading, copy constructor",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day4/CPP_day4",
  pdf:["PD_CPP-DAY4.pdf","Class_board.pdf"],
  img:["Shallow-Deep-copy.png"],
  codeDir:".",codeFilter:"demo",
  mcq:["MCQ_OPPS/Day01_MCQ.pdf","MCQ_OPPS/Day02_MCQ.pdf","MCQ_OPPS/Day03_MCQ.pdf","MCQ_OPPS/Day04_MCQ.pdf"],
  poll:["Poll_OOPS/Day01_POll_Questions.pdf","Poll_OOPS/Day02_POll_Questions.pdf"],
  note:"Complete Assignment_4.txt. Make sure to review the Shallow vs Deep copy diagram."},
 {id:"w5d3",dow:"Wed",date:"2026-10-14",subject:"CPP",topic:"Inheritance, virtual functions, templates",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day5/CPP_day5",
  pdf:["../../PD_CPP-DAY5.pdf","Class-Board_OC21.pdf"],
  codeDir:".",codeFilter:"demo",
  mcq:["../../CPP_day4/CPP_day4/MCQ_OPPS/Day05_MCQ.pdf","../../CPP_day4/CPP_day4/MCQ_OPPS/Day06_MCQ.pdf","../../CPP_day4/CPP_day4/MCQ_OPPS/Day07_MCQ.pdf"],
  poll:["../../CPP_day4/CPP_day4/Poll_OOPS/Day03_POll_Questions.pdf"],
  note:"Solve Assignment_5.txt (Artist/Painter/Singer inheritance).",
  hint:"PD_CPP-DAY5.pdf is one level up (in ObjectOrientedProgramming/), not in the CPP_day5/ folder."},
 {id:"w5d4",dow:"Thu",date:"2026-10-15",subject:"OS",topic:"OS intro, hardware, memory tech, booting",
  folder:"sunbeam os and cf/CF-OS/day1",
  pdf:["Day-1.pdf","classwork.pdf"],
  mcq:["../day2/Day01_MCQ.pdf"],poll:["../day2/Day01_POll_Questions.pdf"],
  hint:"Computer Fundamentals is also in this PDF — Section A's Computer Fundamentals part is covered here."},
 {id:"w5d5",dow:"Fri",date:"2026-10-16",subject:"OS",topic:"System calls, dual mode, process & PCB, states",
  folder:"sunbeam os and cf/CF-OS/day2",
  pdf:["Day-2.pdf","classwork.pdf"],
  mcq:["Day01_MCQ.pdf"],poll:["Day01_POll_Questions.pdf"],
  note:"Memorize the process state diagram — this is guaranteed to appear in the exam."},
 {id:"w5d6",dow:"Sat",date:"2026-10-17",subject:"Practice",topic:"Aptitude Day 5 + C/C++ MCQ revise",
  folder:"suneam apptitude/Aptitude/Day_05",
  tasks:[
   {label:"Read Apti_Day05.pdf",detail:"suneam apptitude/Aptitude/Day_05/Apti_Day05.pdf"},
   {label:"Aptitude MCQs + Poll Day05",detail:"suneam apptitude/Aptitude/MCQs/Day05_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day05_POll_Questions.pdf"},
   {label:"Solve all C MCQ + POLL PDFs",dirs:["C_Programming_ClassWork/CProgramming/MCQ","C_Programming_ClassWork/CProgramming/POLL"]},
   {label:"Solve all C++ output questions from Code_MCQ.txt",detail:"sunbeam cpp/ObjectOrientedProgramming/CPP_day5/CPP_day5/Code_MCQ.txt"}]},
 {id:"w5d7",dow:"Sun",date:"2026-10-18",subject:"Revision",topic:"Rest + C++ revise",folder:null,
  tasks:[   {label:"Revise inheritance modes table (public/private/protected)"}]}]},

{week:6,title:"OS finish + Networking",range:"Mon 19 Oct → Sun 25 Oct",days:[
 {id:"w6d1",dow:"Mon",date:"2026-10-19",subject:"OS",topic:"CPU scheduling algorithms, IPC, sync",
  folder:"sunbeam os and cf/CF-OS/day3",
  pdf:["Day-3.pdf","classwork.pdf"],
  mcq:["Day02_MCQ.pdf"],poll:["Day02_POll_Questions.pdf"],
  hint:"Solve FCFS/SJF/RR numericals by hand — memorizing formulas alone won't work."},
 {id:"w6d2",dow:"Tue",date:"2026-10-20",subject:"OS",topic:"Deadlocks + handling",
  folder:"sunbeam os and cf/CF-OS/day4",
  pdf:["Day-4.pdf","classwork.pdf"],
  extra:["Semaphore.txt"],
  mcq:["Day03_MCQ.pdf"],poll:["Day03_POll_Questions.pdf"],
  note:"4 necessary conditions of deadlock + Banker's algorithm."},
 {id:"w6d3",dow:"Wed",date:"2026-10-21",subject:"OS",topic:"Memory mgmt: paging, segmentation, virtual memory",
  folder:"sunbeam os and cf/CF-OS/day5",
  pdf:["Day-5.pdf","Classwork1.pdf","Classwork2.pdf"],
  extra:["page_R_algo.pdf"],
  mcq:["Day04_MCQ.pdf"],poll:["Day04_POll_Questions.pdf"],
  hint:"Solve one worked example for each page replacement algorithm (FIFO/LRU/Optimal)."},
 {id:"w6d4",dow:"Thu",date:"2026-10-22",subject:"OS",topic:"File systems, disk scheduling",
  folder:"sunbeam os and cf/CF-OS/day6",
  pdf:["Day-6_1.pdf","disk algo.pdf"],
  mcq:["OS_POLL_MCQ_2026/MCQ_OS/Day01_MCQ.pdf","OS_POLL_MCQ_2026/MCQ_OS/Day02_MCQ.pdf","OS_POLL_MCQ_2026/MCQ_OS/Day03_MCQ.pdf"],
  poll:["OS_POLL_MCQ_2026/Poll_OS/Day01_POll_Questions.pdf","OS_POLL_MCQ_2026/Poll_OS/Day02_POll_Questions.pdf"],
  note:"FCFS/SSTF/SCAN/C-SCAN seek-time calculations."},
 {id:"w6d5",dow:"Fri",date:"2026-10-23",subject:"DCN",topic:"Networking: LAN/WAN, OSI layers, IP addressing, TCP/IP",
  folder:"sunbeam dcn/DCN/Day_01",
  pdf:["DCN_Day01.pdf","Day01_Notes.pdf"],
  mcq:["../MCQs/Day01_MCQ.pdf"],poll:["../Poll_Questions/Day01_POll_Questions.pdf"],
  hint:"OSI 7 layers + protocols for each layer — this just has to be memorized."},
 {id:"w6d6",dow:"Sat",date:"2026-10-24",subject:"Practice",topic:"Aptitude Day 6 (English) + DCN MCQs",
  folder:"suneam apptitude/Aptitude/Day_06",
  tasks:[
   {label:"Read Apti_Day06.pdf and Apti_Day06_English.pdf",detail:"suneam apptitude/Aptitude/Day_06/Apti_Day06.pdf\nsuneam apptitude/Aptitude/Day_06/Apti_Day06_English.pdf"},
   {label:"Solve DCN_MCQs.pdf",detail:"sunbeam dcn/DCN/Day_03/DCN_MCQs.pdf"},
   {label:"Revise one topic from English_Data",dir:"suneam apptitude/Aptitude/English_Data"}]},
 {id:"w6d7",dow:"Sun",date:"2026-10-25",subject:"Revision",topic:"Rest + OS revise",folder:null,
  tasks:[   {label:"Revise CPU scheduling + deadlock conditions"}]}]},

{week:7,title:"Networking finish + Big Data",range:"Mon 26 Oct → Sun 1 Nov",days:[
 {id:"w7d1",dow:"Mon",date:"2026-10-26",subject:"DCN",topic:"TCP/IP protocols (ARP, TCP, UDP, DNS, HTTP), IPv6",
  folder:"sunbeam dcn/DCN/Day_02",
  pdf:["DCN_Day02.pdf","Day02_Notes.pdf"],
  mcq:["../MCQs/Day02_MCQ.pdf"],poll:["../Poll_Questions/Day02_POll_Questions.pdf"],
  hint:"Make a TCP vs UDP differences table."},
 {id:"w7d2",dow:"Tue",date:"2026-10-27",subject:"DCN",topic:"DCN wrap-up + MCQs",
  folder:"sunbeam dcn/DCN/Day_03",
  pdf:["DCN_Day03.pdf","Day03_Notes.pdf","DCN_MCQs.pdf"],
  img:["diag.png"],
  mcq:["../MCQs/Day03_MCQ.pdf"],poll:["../Poll_Questions/Day03_POll_Questions.pdf"]},
 {id:"w7d3",dow:"Wed",date:"2026-10-28",subject:"BigData",topic:"Big Data: 5 V's, types of data, batch vs streaming",
  folder:"sunbeam bigdata/BigData/day1",
  pdf:["DataEngg-Day1.pdf"],
  mcq:["Day01_MCQ.pdf"],poll:["Day01_POll_Questions.pdf"]},
 {id:"w7d4",dow:"Thu",date:"2026-10-29",subject:"BigData",topic:"RDBMS/SQL vs NoSQL, CAP, ETL vs ELT, OLAP vs OLTP",
  folder:"sunbeam bigdata/BigData/day2",
  pdf:["DataEngg-day2.pdf"],
  mcq:["Day02_MCQ.pdf"],poll:["Day02_POll_Questions.pdf"],
  hint:"ACID vs BASE + CAP theorem — only 3 short topics, don't spend too much time."},
 {id:"w7d5",dow:"Fri",date:"2026-10-30",subject:"BigData",topic:"Hadoop, Hive, Spark intro, careers",
  folder:"sunbeam bigdata/BigData/day3",
  pdf:["DataEngg-Day3.pdf"],
  mcq:["Day03_MCQ.pdf"],poll:["Day03_POll_Questions.pdf"]},
 {id:"w7d6",dow:"Sat",date:"2026-10-31",subject:"Practice",topic:"Aptitude Day 7 (Reasoning) + BigData MCQs",
  folder:"suneam apptitude/Aptitude/Day_07",
  tasks:[
   {label:"Read Apti_Day07_Reasoning.pdf",detail:"suneam apptitude/Aptitude/Day_07/Apti_Day07_Reasoning.pdf"},
   {label:"Solve all BigData MCQs + Polls",dirs:["sunbeam bigdata/BigData/day1","sunbeam bigdata/BigData/day2","sunbeam bigdata/BigData/day3"]},
   {label:"Practice one chapter from RS Aggarwal Reasoning",detail:"suneam apptitude/Aptitude/RS Aggarwal reasoning .pdf"}]},
 {id:"w7d7",dow:"Sun",date:"2026-11-01",subject:"Revision",topic:"Rest + DCN skim",folder:null,
  tasks:[   {label:"Skim DCN notes"}]}]},

{week:8,title:"AI + Full Revision + Mocks",range:"Mon 2 Nov → Sun 8 Nov",days:[
 {id:"w8d1",dow:"Mon",date:"2026-11-02",subject:"AI",topic:"AI: agents, types of AI, ML vs DL basics",
  folder:"sun/Artificial-Intelligence/Day_01",
  pdf:["AI_Day01.pdf","AI_Day01_notes.pdf"],
  mcq:["../MCQs/Day01_MCQ.pdf"],poll:["../Poll_Questions/Day01_POll_Questions.pdf"]},
 {id:"w8d2",dow:"Tue",date:"2026-11-03",subject:"AI",topic:"Neural networks, fuzzy logic, trends",
  folder:"sun/Artificial-Intelligence/Day_02",
  pdf:["AI_Day02.pdf","AI_Day02_notes.pdf"],
  extra:["AI_MCQs.txt  (50 solved questions — revise them)"],
  mcq:["../MCQs/Day02_MCQ.pdf"],poll:["../Poll_Questions/Day02_POll_Questions.pdf"],
  hint:"Section B complete! Now enter revision + mock mode."},
 {id:"w8d3",dow:"Wed",date:"2026-11-04",subject:"Revision",topic:"Full revision 1: C + DS",folder:null,
  tasks:[
   {label:"Solve all C MCQ + POLL",dirs:["C_Programming_ClassWork/CProgramming/MCQ","C_Programming_ClassWork/CProgramming/POLL"]},
   {label:"Solve all DS MCQs + Polls",dirs:["sunbeam data structure/DataStructure/MCQ","sunbeam data structure/DataStructure/Poll_Questions"]},
   {label:"Re-solve c quize.txt",detail:"quize pdfs/c quize.txt"}]},
 {id:"w8d4",dow:"Thu",date:"2026-11-05",subject:"Revision",topic:"Full revision 2: C++ + OS + DCN + BigData + AI",folder:null,
  tasks:[
   {label:"Re-solve Code_MCQ.txt",detail:"sunbeam cpp/ObjectOrientedProgramming/CPP_day5/CPP_day5/Code_MCQ.txt"},
   {label:"Solve all CPP MCQs + Polls",dirs:["sunbeam cpp/ObjectOrientedProgramming/CPP_day4/CPP_day4/MCQ_OPPS","sunbeam cpp/ObjectOrientedProgramming/CPP_day4/CPP_day4/Poll_OOPS"]},
   {label:"Solve all OS MCQs + Polls",dirs:["sunbeam os and cf/CF-OS/day2","sunbeam os and cf/CF-OS/day3","sunbeam os and cf/CF-OS/day4","sunbeam os and cf/CF-OS/day5","sunbeam os and cf/CF-OS/day6/OS_POLL_MCQ_2026/MCQ_OS","sunbeam os and cf/CF-OS/day6/OS_POLL_MCQ_2026/Poll_OS"]},
   {label:"Solve DCN + BigData + AI MCQ/Poll sets",dirs:["sunbeam dcn/DCN/MCQs","sunbeam dcn/DCN/Poll_Questions","sunbeam bigdata/BigData/day1","sunbeam bigdata/BigData/day2","sunbeam bigdata/BigData/day3","sun/Artificial-Intelligence/MCQs","sun/Artificial-Intelligence/Poll_Questions"]}]},
 {id:"w8d5",dow:"Fri",date:"2026-11-06",subject:"Mock",topic:"Mock C-CAT #1 (100 Qs, A+B, timed, −1 marking)",
  folder:null,
  tasks:[
   {label:"Section A: 50 Qs — solve with a 1-hour timer"},
   {label:"Section B: 50 Qs — 1 hour"},
   {label:"Enter score in Mock Log tab (+3 / −1 marking)"}]},  {id:"w8d6",dow:"Sat",date:"2026-11-07",subject:"Mock",topic:"Mock #2 + fix every wrong question",
  folder:null,
  tasks:[
   {label:"Take Mock #2 and enter score in Mock Log"},
   {label:"Log whatever you got wrong in the Weak Topics tab"},
   {label:"Understand the reason for each wrong answer — don't just look at the answer"}]},
 {id:"w8d7",dow:"Sun",date:"2026-11-08",subject:"Revision",topic:"Light day: formula sheet + relax",folder:null,
  tasks:[
   {label:"Read formule.txt and notes.txt",dir:"sunbeam practices"},
   {label:"Revise bitwise operator formulas"},
   {label:"Nothing new today — give your brain a rest"}]}]}
];
