import type { Week } from "./types";

/**
 * The 8-week study plan, ported verbatim from Study_Dashboard.html.
 * Every path in here is relative to the vault and resolves against data/manifest.json.
 */
export const PLAN: Week[] = [
{week:1,title:"C Basics",range:"Mon 14 Sep → Sun 20 Sep",days:[
 {id:"w1d1",dow:"Mon",date:"2026-09-14",subject:"C",topic:"What is C, how a program runs, main(), printf, tokens",
  folder:"C_Programming_ClassWork/CProgramming/Day1",
  pdf:["C_Programming_Day1.pdf","C_Programming_Day2.pdf","Diagram_CProg_Day1_Part1.pdf","Diagram_CProgramming_Dat1_Part2.xopp"],
  img:["ASCII.png","ProgramFuncStmt_Token.png"],
  codeDir:"code",
  mcq:["../MCQ/Day01_MCQ.pdf"],poll:["../POLL/Day01_POll_Questions.pdf"],
  hint:"Foundation din. C strong hua to DS + C++ aasan ho jayega."},
 {id:"w1d2",dow:"Tue",date:"2026-09-15",subject:"C",topic:"Identifiers, keywords, data types, variables",
  folder:"C_Programming_ClassWork/CProgramming/Day2",
  pdf:["C_Programming_Day1.pdf","C_Programming_Day3.pdf","C_Programming_Day4.pdf","Diagram_Day3_CProg.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day02_MCQ.pdf"],poll:["../POLL/Day02_POll_Questions.pdf"],
  hint:"Folder naming off-by-one: Day2 ka actual lecture C_Programming_Day2.pdf Day1/ folder me hai."},
 {id:"w1d3",dow:"Wed",date:"2026-09-16",subject:"C",topic:"Operators (priority & associativity)",
  folder:"C_Programming_ClassWork/CProgramming/Day3",
  pdf:["C_Programming_Day4.pdf","Diagrams_CProg_Day3.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day03_MCQ.pdf"],poll:["../POLL/Day03_POll_Questions.pdf"],
  hint:"Day3 ka lecture C_Programming_Day3.pdf pichle folder (Day2/) me hai. Diagrams sahi jagah hain."},
 {id:"w1d4",dow:"Thu",date:"2026-09-17",subject:"C",topic:"Control flow: if / else, switch",
  folder:"C_Programming_ClassWork/CProgramming/Day4",
  pdf:["Day5.pdf","Day6.pdf","Diagrams_CProg_Day4_Part1.pdf","Diagrams_CProg_Day4_Part2.pdf"],
  img:["Screenshot 2024-04-12 120112.png","Screenshot 2024-04-12 120146.png","Screenshot 2024-04-12 121529.png","Screenshot 2024-04-12 121554.png","Screenshot 2024-11-18 113419.png","Screenshot 2024-11-18 113542.png","Screenshot 2024-11-18 113606.png","Screenshot 2024-11-18 113637.png"],
  codeDir:"code",
  mcq:["../MCQ/Day04_MCQ.pdf"],poll:["../POLL/Day04_POll_Questions.pdf"],
  hint:"Day4 ka lecture C_Programming_Day4.pdf Day3/ (aur Day2/) me hai."},
 {id:"w1d5",dow:"Fri",date:"2026-09-18",subject:"C",topic:"Loops: while, do-while, for",
  folder:"C_Programming_ClassWork/CProgramming/Day5",
  pdf:["Day7.pdf","Day8.pdf","Diagram_CProg_Day5_Part1.pdf","Diagram_CProg_Day5_Part2.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day05_MCQ.pdf"],poll:["../POLL/Day05_POll_Questions.pdf"]},
 {id:"w1d6",dow:"Sat",date:"2026-09-19",subject:"Practice",topic:"Week-1 revision + Aptitude Day 1",
  folder:"suneam apptitude/Aptitude/Day_01",
  tasks:[
   {label:"Week 1 ke saare demo .c files memory se dobara likho aur run karo",dirs:["C_Programming_ClassWork/CProgramming/Day1/code","C_Programming_ClassWork/CProgramming/Day2/code","C_Programming_ClassWork/CProgramming/Day3/code","C_Programming_ClassWork/CProgramming/Day4/code","C_Programming_ClassWork/CProgramming/Day5/code"]},
   {label:"Aptitude Day_01 lecture padho",detail:"suneam apptitude/Aptitude/Day_01/Apti_Day01.pdf"},
   {label:"Aptitude MCQs + Poll solve karo",detail:"suneam apptitude/Aptitude/MCQs/Day01_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day01_POll_Questions.pdf"}]},
 {id:"w1d7",dow:"Sun",date:"2026-09-20",subject:"Revision",topic:"Rest + week revise",
  folder:null,
  tasks:[
   {label:"Week 1 ke PDFs dobara skim karo"},
   {label:"Jo MCQ galat hue unhe bina dekhe dobara solve karo"},
   {label:"Weak Topics tab me is week ki galtiyan likh do"}]}]},

{week:2,title:"C Core",range:"Mon 21 Sep → Sun 27 Sep",days:[
 {id:"w2d1",dow:"Mon",date:"2026-09-21",subject:"C",topic:"Functions, pass by value vs address, recursion",
  folder:"C_Programming_ClassWork/CProgramming/Day6",
  pdf:["Day8.pdf","Day9.pdf","Day10.pdf","Diagrams_CProg_Day6_Part1.pdf","Diagrams_CProg_Day6_Part2.pdf","Diagrams_CProg_Day6_Part3.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day06_MCQ.pdf"],poll:["../POLL/Day06_POll_Questions.pdf"],
  hint:"Pass by value vs address ye exam ka favourite hai — dono ke saath ek-ek program likho."},
 {id:"w2d2",dow:"Tue",date:"2026-09-22",subject:"C",topic:"Storage classes, scope",
  folder:"C_Programming_ClassWork/CProgramming/Day7",
  pdf:["Day9.pdf","Day10.pdf","Diagram_CProg_Day7.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day07_MCQ.pdf"],poll:["../POLL/Day07_POll_Questions.pdf"],
  hint:"auto / static / extern / register — output-prediction questions yahin se aate hain."},
 {id:"w2d3",dow:"Wed",date:"2026-09-23",subject:"C",topic:"Arrays (1D, 2D)",
  folder:"C_Programming_ClassWork/CProgramming/Day8",
  pdf:["Day10.pdf","Diagrams_CProg_Day8.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day08_MCQ.pdf"],poll:["../POLL/Day08_POll_Questions.pdf"]},
 {id:"w2d4",dow:"Thu",date:"2026-09-24",subject:"C",topic:"Strings + library functions",
  folder:"C_Programming_ClassWork/CProgramming/Day9",
  pdf:["Day10.pdf","Day13.pdf","Diagram_CProg_Day9_annotated.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day09_MCQ.pdf"],poll:["../POLL/Day09_POll_Questions.pdf"]},
 {id:"w2d5",dow:"Fri",date:"2026-09-25",subject:"C",topic:"Pointers: wild / NULL / void, pointer arithmetic",
  folder:"C_Programming_ClassWork/CProgramming/Day10",
  pdf:["Day13.pdf","Diagram_CProg_Day10.pdf"],
  mcq:["../MCQ/Day10_MCQ.pdf"],poll:["../POLL/Day10_POll_Questions.pdf"],
  hint:"Is din koi code/ folder nahi hai — khud ke programs likho. Pointers = sabse zyada marks wala topic."},
 {id:"w2d6",dow:"Sat",date:"2026-09-26",subject:"Practice",topic:"Aptitude Day 2 + ab tak ke quiz",
  folder:"suneam apptitude/Aptitude/Day_02",
  tasks:[
   {label:"Apti_Day02.pdf padho",detail:"suneam apptitude/Aptitude/Day_02/Apti_Day02.pdf"},
   {label:"Apti MCQs + Poll Day02 solve karo",detail:"suneam apptitude/Aptitude/MCQs/Day02_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day02_POll_Questions.pdf"},
   {label:"c quize.txt ke output-prediction questions solve karo",detail:"quize pdfs/c quize.txt  (20 questions)"},
   {label:"Quiz PDFs me se C wale questions karo",detail:"quize pdfs/Quiz_Questions_and_Solutions.pdf"}]},
 {id:"w2d7",dow:"Sun",date:"2026-09-27",subject:"Revision",topic:"Rest + week revise",
  folder:null,
  tasks:[{label:"Week 2 ke PDFs skim karo"},{label:"'Mid-point check: ~70% C syllabus done' — khud ko test karo"}]}]},

{week:3,title:"C finishing + Data Structures",range:"Mon 28 Sep → Sun 4 Oct",days:[
 {id:"w3d1",dow:"Mon",date:"2026-09-28",subject:"C",topic:"Pointers + arrays, dynamic memory (malloc/free)",
  folder:"C_Programming_ClassWork/CProgramming/Day11",
  pdf:["Day13.pdf","Day15.pdf","Diagram_CProg_Day11.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day11_MCQ.pdf"],poll:["../POLL/Day11_POll_Questions.pdf"],
  hint:"malloc/free + memory leak questions pakka aate hain."},
 {id:"w3d2",dow:"Tue",date:"2026-09-29",subject:"C",topic:"Structures, unions, bit fields",
  folder:"C_Programming_ClassWork/CProgramming/Day12",
  pdf:["Day15_1.pdf","Diagrams_CProg_Day12_Part1.pdf","Diagrams_CProg_Day12_Part2.pdf","Final_Day18.pdf"],
  codeDir:"code",
  mcq:["../MCQ/Day12_MCQ.pdf"],poll:["../POLL/Day12_POll_Questions.pdf"],
  hint:"struct vs union ka size — calculation karne ki aadat daalo."},
 {id:"w3d3",dow:"Wed",date:"2026-09-30",subject:"C",topic:"Preprocessor, file handling",
  folder:"C_Programming_ClassWork/CProgramming/Day13",
  pdf:["Day18.pdf","Diagram_CProg_Day17.pdf"],
  img:["Screenshot 2024-10-17 115041.png"],
  codeDir:"code",
  mcq:["../MCQ/Day13_MCQ.pdf"],poll:["../POLL/Day13_POll_Questions.pdf"],
  hint:"Yahan C syllabus khatam. POLL folder me Day14–Day18 ke extra sets bhi hain — bonus practice."},
 {id:"w3d4",dow:"Thu",date:"2026-10-01",subject:"DS",topic:"Complexity (best/avg/worst) + sorting intro",
  folder:"sunbeam data structure/DataStructure/Day01",
  pdf:["Day1.pdf"],
  codeDir:"codes",
  extraDir:"diagrams",
  mcq:["MCQ/Day01_MCQ.pdf"],poll:["Poll_Questions/Day01_POll_Questions.pdf"],
  hint:"Time_Space_Complexity.xlsx kholo — isko yaad karne se poora DS section half aasan ho jata hai."},
 {id:"w3d5",dow:"Fri",date:"2026-10-02",subject:"DS",topic:"Sorting: selection, bubble, insertion",
  folder:"sunbeam data structure/DataStructure/Day02",
  pdf:["Day2_1.pdf","Day2_2.pdf"],
  extraDir:"diagrams",
  mcq:["MCQ/Day02_MCQ.pdf"],poll:["Poll_Questions/Day02_POll_Questions.pdf"]},
 {id:"w3d6",dow:"Sat",date:"2026-10-03",subject:"Practice",topic:"Aptitude Day 3 + poll questions",
  folder:"suneam apptitude/Aptitude/Day_03",
  tasks:[
   {label:"Apti_Day03.pdf padho",detail:"suneam apptitude/Aptitude/Day_03/Apti_Day03.pdf"},
   {label:"Aptitude MCQs + Poll Day03 solve karo",detail:"suneam apptitude/Aptitude/MCQs/Day03_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day03_POll_Questions.pdf"},
   {label:"Week 1–3 ke C POLL questions dobara solve karo",dir:"C_Programming_ClassWork/CProgramming/POLL"},
   {label:"C MCQ sheet ke saare Day01–Day15 solve karo",dir:"C_Programming_ClassWork/CProgramming/MCQ"}]},
 {id:"w3d7",dow:"Sun",date:"2026-10-04",subject:"Revision",topic:"Rest",folder:null,
  tasks:[{label:"Rest. Chaaho to sorting complexities ka table revise karo"}]}]},

{week:4,title:"Data Structures + C++ start",range:"Mon 5 Oct → Sun 11 Oct",days:[
 {id:"w4d1",dow:"Mon",date:"2026-10-05",subject:"DS",topic:"Merge sort, quick sort, binary/linear search",
  folder:"sunbeam data structure/DataStructure/Day03",
  pdf:[],
  extraDir:"diagrams",
  mcq:["../MCQ/Day03_MCQ.pdf"],poll:["../Poll_Questions/Day03_POll_Questions.pdf"],
  hint:"DS Day03 me lecture PDF nahi hai — sirf linked-list diagrams hain. Merge/Quick sort ke notes Day02/Day05 PDFs + YouTube se cover karo."},
 {id:"w4d2",dow:"Tue",date:"2026-10-06",subject:"DS",topic:"Stack + queue (types, applications, expression conversion)",
  folder:"sunbeam data structure/DataStructure/Day04",
  pdf:[],
  extraDir:"diagrams",
  mcq:["../MCQ/Day04_MCQ.pdf"],poll:["../Poll_Questions/Day04_POll_Questions.pdf"],
  hint:"Is folder me bhi sirf diagrams hain. Infix→Postfix conversion khud se practice karo, wahi exam me aata hai."},
 {id:"w4d3",dow:"Wed",date:"2026-10-07",subject:"DS",topic:"Linked lists, trees, graphs",
  folder:"sunbeam data structure/DataStructure/Day05",
  pdf:["Trees.pdf","HashTable.pdf","graph.pdf"],
  extraDir:"diagrams",
  mcq:["../MCQ/Day05_MCQ.pdf"],poll:["../Poll_Questions/Day05_POll_Questions.pdf"]},
 {id:"w4d4",dow:"Thu",date:"2026-10-08",subject:"CPP",topic:"C++ basics: cin/cout, class/object, struct vs class",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day1/CPP_day1",
  pdf:["PD_CPP-DAY1.pdf","Class_board.pdf"],
  codeDir:".",codeFilter:"demo",
  mcq:["../../CPP_day2/CPP_day2/Day01_MCQ.pdf"],
  note:"Assignment_1.txt me 5 programs hain — sab likho.",
  hint:"Pehla assigment: same employee struct .c aur .cpp dono me — farak khud dekho."},
 {id:"w4d5",dow:"Fri",date:"2026-10-09",subject:"CPP",topic:"Constructors, destructors, inline, default args",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day2/CPP_day2",
  pdf:["PD_CPP-DAY2.pdf","Class-Board_OC21.pdf"],
  codeDir:".",codeFilter:"demo",
  mcq:["Day02_MCQ.pdf"],poll:["Day02_POll_Questions.pdf","Day03_POll_Questions.pdf"],
  note:"Assignment_2.txt complete karo."},
 {id:"w4d6",dow:"Sat",date:"2026-10-10",subject:"Practice",topic:"Aptitude Day 4 + DS quiz",
  folder:"suneam apptitude/Aptitude/Day_04",
  tasks:[
   {label:"Apti_Day04.pdf padho",detail:"suneam apptitude/Aptitude/Day_04/Apti_Day04.pdf"},
   {label:"Aptitude MCQs + Poll Day04",detail:"suneam apptitude/Aptitude/MCQs/Day04_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day04_POll_Questions.pdf"},
   {label:"DS ke saare MCQ dobara solve karo",dir:"sunbeam data structure/DataStructure/MCQ"},
   {label:"DS ke saare Poll questions dobara solve karo",dir:"sunbeam data structure/DataStructure/Poll_Questions"}]},
 {id:"w4d7",dow:"Sun",date:"2026-10-11",subject:"Revision",topic:"Rest + DS revise",folder:null,
  tasks:[{label:"Sorting complexities ka table revise karo (Time_Space_Complexity.xlsx)"}]}]},

{week:5,title:"C++ finish + OS start",range:"Mon 12 Oct → Sun 18 Oct",days:[
 {id:"w5d1",dow:"Mon",date:"2026-10-12",subject:"CPP",topic:"new/delete, references, static members, friend",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day3/CPP_day3",
  pdf:["PD_CPP-DAY3.pdf","Class_board.pdf"],
  codeDir:".",codeFilter:"demo",
  note:"Assignment_2.txt (Day3 wala) complete karo.",
  hint:"Reference variable + static = Code_MCQ.txt me sabse zyada questions inhi se hain."},
 {id:"w5d2",dow:"Tue",date:"2026-10-13",subject:"CPP",topic:"Function/operator overloading, copy constructor",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day4/CPP_day4",
  pdf:["PD_CPP-DAY4.pdf","Class_board.pdf"],
  img:["Shallow-Deep-copy.png"],
  codeDir:".",codeFilter:"demo",
  mcq:["MCQ_OPPS/Day01_MCQ.pdf","MCQ_OPPS/Day02_MCQ.pdf","MCQ_OPPS/Day03_MCQ.pdf","MCQ_OPPS/Day04_MCQ.pdf"],
  poll:["Poll_OOPS/Day01_POll_Questions.pdf","Poll_OOPS/Day02_POll_Questions.pdf"],
  note:"Assignment_4.txt complete karo. Shallow vs Deep copy wala diagram zaroor dekho."},
 {id:"w5d3",dow:"Wed",date:"2026-10-14",subject:"CPP",topic:"Inheritance, virtual functions, templates",
  folder:"sunbeam cpp/ObjectOrientedProgramming/CPP_day5/CPP_day5",
  pdf:["../../PD_CPP-DAY5.pdf","Class-Board_OC21.pdf"],
  codeDir:".",codeFilter:"demo",
  mcq:["../../CPP_day4/CPP_day4/MCQ_OPPS/Day05_MCQ.pdf","../../CPP_day4/CPP_day4/MCQ_OPPS/Day06_MCQ.pdf","../../CPP_day4/CPP_day4/MCQ_OPPS/Day07_MCQ.pdf"],
  poll:["../../CPP_day4/CPP_day4/Poll_OOPS/Day03_POll_Questions.pdf"],
  note:"Assignment_5.txt (Artist/Painter/Singer inheritance) solve karo.",
  hint:"PD_CPP-DAY5.pdf ek level upar (ObjectOrientedProgramming/ me) hai, CPP_day5/ folder me nahi."},
 {id:"w5d4",dow:"Thu",date:"2026-10-15",subject:"OS",topic:"OS intro, hardware, memory tech, booting",
  folder:"sunbeam os and cf/CF-OS/day1",
  pdf:["Day-1.pdf","classwork.pdf"],
  mcq:["../day2/Day01_MCQ.pdf"],poll:["../day2/Day01_POll_Questions.pdf"],
  hint:"Computer Fundamentals bhi isi PDF me hai — Section A ka Computer Fundamentals part yahin se cover hota hai."},
 {id:"w5d5",dow:"Fri",date:"2026-10-16",subject:"OS",topic:"System calls, dual mode, process & PCB, states",
  folder:"sunbeam os and cf/CF-OS/day2",
  pdf:["Day-2.pdf","classwork.pdf"],
  mcq:["Day01_MCQ.pdf"],poll:["Day01_POll_Questions.pdf"],
  note:"Process state diagram yaad kar lo — pakka question aata hai."},
 {id:"w5d6",dow:"Sat",date:"2026-10-17",subject:"Practice",topic:"Aptitude Day 5 + C/C++ MCQ revise",
  folder:"suneam apptitude/Aptitude/Day_05",
  tasks:[
   {label:"Apti_Day05.pdf padho",detail:"suneam apptitude/Aptitude/Day_05/Apti_Day05.pdf"},
   {label:"Aptitude MCQs + Poll Day05",detail:"suneam apptitude/Aptitude/MCQs/Day05_MCQ.pdf\nsuneam apptitude/Aptitude/Poll_Questions/Day05_POll_Questions.pdf"},
   {label:"C ke saare MCQ + POLL pdfs solve karo",dirs:["C_Programming_ClassWork/CProgramming/MCQ","C_Programming_ClassWork/CProgramming/POLL"]},
   {label:"Code_MCQ.txt ke saare C++ output questions solve karo",detail:"sunbeam cpp/ObjectOrientedProgramming/CPP_day5/CPP_day5/Code_MCQ.txt"}]},
 {id:"w5d7",dow:"Sun",date:"2026-10-18",subject:"Revision",topic:"Rest + C++ revise",folder:null,
  tasks:[{label:"Inheritance modes ka table revise karo (public/private/protected)"}]}]},

{week:6,title:"OS finish + Networking",range:"Mon 19 Oct → Sun 25 Oct",days:[
 {id:"w6d1",dow:"Mon",date:"2026-10-19",subject:"OS",topic:"CPU scheduling algorithms, IPC, sync",
  folder:"sunbeam os and cf/CF-OS/day3",
  pdf:["Day-3.pdf","classwork.pdf"],
  mcq:["Day02_MCQ.pdf"],poll:["Day02_POll_Questions.pdf"],
  hint:"FCFS/SJF/RR ke numericals haath se solve karo — formula ratne se kaam nahi chalega."},
 {id:"w6d2",dow:"Tue",date:"2026-10-20",subject:"OS",topic:"Deadlocks + handling",
  folder:"sunbeam os and cf/CF-OS/day4",
  pdf:["Day-4.pdf","classwork.pdf"],
  extra:["Semaphore.txt"],
  mcq:["Day03_MCQ.pdf"],poll:["Day03_POll_Questions.pdf"],
  note:"4 necessary conditions of deadlock + Banker's algorithm."},
 {id:"w6d3",dow:"Wed",date:"2026-10-21",subject:"OS",topic:"Memory mgmt: paging, segmentation, virtual memory",
  folder:"sunbeam os and cf/CF-OS/day5",
  pdf:["Day-5.pdf","Classwork1.pdf","Classwork2.pdf"],
  extra:["page_R_algo.pdf"],
  mcq:["Day04_MCQ.pdf"],poll:["Day04_POll_Questions.pdf"],
  hint:"Page replacement algorithms (FIFO/LRU/Optimal) ka ek-ek solved example karo."},
 {id:"w6d4",dow:"Thu",date:"2026-10-22",subject:"OS",topic:"File systems, disk scheduling",
  folder:"sunbeam os and cf/CF-OS/day6",
  pdf:["Day-6_1.pdf","disk algo.pdf"],
  mcq:["OS_POLL_MCQ_2026/MCQ_OS/Day01_MCQ.pdf","OS_POLL_MCQ_2026/MCQ_OS/Day02_MCQ.pdf","OS_POLL_MCQ_2026/MCQ_OS/Day03_MCQ.pdf"],
  poll:["OS_POLL_MCQ_2026/Poll_OS/Day01_POll_Questions.pdf","OS_POLL_MCQ_2026/Poll_OS/Day02_POll_Questions.pdf"],
  note:"FCFS/SSTF/SCAN/C-SCAN seek-time calculations."},
 {id:"w6d5",dow:"Fri",date:"2026-10-23",subject:"DCN",topic:"Networking: LAN/WAN, OSI layers, IP addressing, TCP/IP",
  folder:"sunbeam dcn/DCN/Day_01",
  pdf:["DCN_Day01.pdf","Day01_Notes.pdf"],
  mcq:["../MCQs/Day01_MCQ.pdf"],poll:["../Poll_Questions/Day01_POll_Questions.pdf"],
  hint:"OSI ke 7 layers + har layer ke protocols — ye ratta maarna hi padta hai."},
 {id:"w6d6",dow:"Sat",date:"2026-10-24",subject:"Practice",topic:"Aptitude Day 6 (English) + DCN MCQs",
  folder:"suneam apptitude/Aptitude/Day_06",
  tasks:[
   {label:"Apti_Day06.pdf aur Apti_Day06_English.pdf padho",detail:"suneam apptitude/Aptitude/Day_06/Apti_Day06.pdf\nsuneam apptitude/Aptitude/Day_06/Apti_Day06_English.pdf"},
   {label:"DCN_MCQs.pdf solve karo",detail:"sunbeam dcn/DCN/Day_03/DCN_MCQs.pdf"},
   {label:"English_Data se ek topic revise karo",dir:"suneam apptitude/Aptitude/English_Data"}]},
 {id:"w6d7",dow:"Sun",date:"2026-10-25",subject:"Revision",topic:"Rest + OS revise",folder:null,
  tasks:[{label:"CPU scheduling + deadlock conditions revise karo"}]}]},

{week:7,title:"Networking finish + Big Data",range:"Mon 26 Oct → Sun 1 Nov",days:[
 {id:"w7d1",dow:"Mon",date:"2026-10-26",subject:"DCN",topic:"TCP/IP protocols (ARP, TCP, UDP, DNS, HTTP), IPv6",
  folder:"sunbeam dcn/DCN/Day_02",
  pdf:["DCN_Day02.pdf","Day02_Notes.pdf"],
  mcq:["../MCQs/Day02_MCQ.pdf"],poll:["../Poll_Questions/Day02_POll_Questions.pdf"],
  hint:"TCP vs UDP ke differences table bana lo."},
 {id:"w7d2",dow:"Tue",date:"2026-10-27",subject:"DCN",topic:"DCN wrap-up + MCQs",
  folder:"sunbeam dcn/DCN/Day_03",
  pdf:["DCN_Day03.pdf","Day03_Notes.pdf","DCN_MCQs.pdf"],
  img:["diag.png"],
  mcq:["../MCQs/Day03_MCQ.pdf"],poll:["../Poll_Questions/Day03_POll_Questions.pdf"]},
 {id:"w7d3",dow:"Wed",date:"2026-10-28",subject:"BigData",topic:"Big Data: 5 V's, types of data, batch vs streaming",
  folder:"sunbeam bigdata/BigData/day1",
  pdf:["DataEngg-Day1.pdf"],
  mcq:["Day01_MCQ.pdf"],poll:["Day01_POll_Questions.pdf"]},
 {id:"w7d4",dow:"Thu",date:"2026-10-29",subject:"BigData",topic:"RDBMS/SQL vs NoSQL, CAP, ETL vs ELT, OLAP vs OLTP",
  folder:"sunbeam bigdata/BigData/day2",
  pdf:["DataEngg-day2.pdf"],
  mcq:["Day02_MCQ.pdf"],poll:["Day02_POll_Questions.pdf"],
  hint:"ACID vs BASE + CAP theorem — sirf 3 short topics, zyada time mat lagao."},
 {id:"w7d5",dow:"Fri",date:"2026-10-30",subject:"BigData",topic:"Hadoop, Hive, Spark intro, careers",
  folder:"sunbeam bigdata/BigData/day3",
  pdf:["DataEngg-Day3.pdf"],
  mcq:["Day03_MCQ.pdf"],poll:["Day03_POll_Questions.pdf"]},
 {id:"w7d6",dow:"Sat",date:"2026-10-31",subject:"Practice",topic:"Aptitude Day 7 (Reasoning) + BigData MCQs",
  folder:"suneam apptitude/Aptitude/Day_07",
  tasks:[
   {label:"Apti_Day07_Reasoning.pdf padho",detail:"suneam apptitude/Aptitude/Day_07/Apti_Day07_Reasoning.pdf"},
   {label:"BigData ke saare MCQ + Poll solve karo",dirs:["sunbeam bigdata/BigData/day1","sunbeam bigdata/BigData/day2","sunbeam bigdata/BigData/day3"]},
   {label:"RS Aggarwal Reasoning me se ek chapter practice karo",detail:"suneam apptitude/Aptitude/RS Aggarwal reasoning .pdf"}]},
 {id:"w7d7",dow:"Sun",date:"2026-11-01",subject:"Revision",topic:"Rest + DCN skim",folder:null,
  tasks:[{label:"DCN notes skim karo"}]}]},

{week:8,title:"AI + Full Revision + Mocks",range:"Mon 2 Nov → Sun 8 Nov",days:[
 {id:"w8d1",dow:"Mon",date:"2026-11-02",subject:"AI",topic:"AI: agents, types of AI, ML vs DL basics",
  folder:"sun/Artificial-Intelligence/Day_01",
  pdf:["AI_Day01.pdf","AI_Day01_notes.pdf"],
  mcq:["../MCQs/Day01_MCQ.pdf"],poll:["../Poll_Questions/Day01_POll_Questions.pdf"]},
 {id:"w8d2",dow:"Tue",date:"2026-11-03",subject:"AI",topic:"Neural networks, fuzzy logic, trends",
  folder:"sun/Artificial-Intelligence/Day_02",
  pdf:["AI_Day02.pdf","AI_Day02_notes.pdf"],
  extra:["AI_MCQs.txt  (50 solved questions — revise karo)"],
  mcq:["../MCQs/Day02_MCQ.pdf"],poll:["../Poll_Questions/Day02_POll_Questions.pdf"],
  hint:"Section B khatam! Ab revision + mock mode."},
 {id:"w8d3",dow:"Wed",date:"2026-11-04",subject:"Revision",topic:"Full revision 1: C + DS",folder:null,
  tasks:[
   {label:"C ke saare MCQ + POLL solve karo",dirs:["C_Programming_ClassWork/CProgramming/MCQ","C_Programming_ClassWork/CProgramming/POLL"]},
   {label:"DS ke saare MCQ + Poll solve karo",dirs:["sunbeam data structure/DataStructure/MCQ","sunbeam data structure/DataStructure/Poll_Questions"]},
   {label:"c quize.txt dobara solve karo",detail:"quize pdfs/c quize.txt"}]},
 {id:"w8d4",dow:"Thu",date:"2026-11-05",subject:"Revision",topic:"Full revision 2: C++ + OS + DCN + BigData + AI",folder:null,
  tasks:[
   {label:"Code_MCQ.txt dobara solve karo",detail:"sunbeam cpp/ObjectOrientedProgramming/CPP_day5/CPP_day5/Code_MCQ.txt"},
   {label:"CPP ke saare MCQ + Poll solve karo",dirs:["sunbeam cpp/ObjectOrientedProgramming/CPP_day4/CPP_day4/MCQ_OPPS","sunbeam cpp/ObjectOrientedProgramming/CPP_day4/CPP_day4/Poll_OOPS"]},
   {label:"OS ke saare MCQ + Poll solve karo",dirs:["sunbeam os and cf/CF-OS/day2","sunbeam os and cf/CF-OS/day3","sunbeam os and cf/CF-OS/day4","sunbeam os and cf/CF-OS/day5","sunbeam os and cf/CF-OS/day6/OS_POLL_MCQ_2026/MCQ_OS","sunbeam os and cf/CF-OS/day6/OS_POLL_MCQ_2026/Poll_OS"]},
   {label:"DCN + BigData + AI ke MCQ/Poll sets solve karo",dirs:["sunbeam dcn/DCN/MCQs","sunbeam dcn/DCN/Poll_Questions","sunbeam bigdata/BigData/day1","sunbeam bigdata/BigData/day2","sunbeam bigdata/BigData/day3","sun/Artificial-Intelligence/MCQs","sun/Artificial-Intelligence/Poll_Questions"]}]},
 {id:"w8d5",dow:"Fri",date:"2026-11-06",subject:"Mock",topic:"Mock C-CAT #1 (100 Qs, A+B, timed, −1 marking)",
  folder:null,
  tasks:[
   {label:"Section A: 50 Qs — 1 ghante ka timer laga ke solve karo"},
   {label:"Section B: 50 Qs — 1 ghanta"},
   {label:"Score ko Mock Log tab me daalo (+3 / −1 ke saath)"}]},
 {id:"w8d6",dow:"Sat",date:"2026-11-07",subject:"Mock",topic:"Mock #2 + har galat question fix karo",
  folder:null,
  tasks:[
   {label:"Mock #2 do aur score Mock Log me daalo"},
   {label:"Jo bhi galat hua, uska topic Weak Topics me likho"},
   {label:"Har galat question ka reason samjho — sirf answer mat dekho"}]},
 {id:"w8d7",dow:"Sun",date:"2026-11-08",subject:"Revision",topic:"Light day: formula sheet + relax",folder:null,
  tasks:[
   {label:"formule.txt aur notes.txt padho",dir:"sunbeam practices"},
   {label:"Bitwise operators ke formulas revise karo"},
   {label:"Aaj naya kuch nahi — dimaag rest do"}]}]}
];
